// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A [CaPool][google.cloud.security.privateca.v1.CaPool] represents a group of
/// [CertificateAuthorities][google.cloud.security.privateca.v1.CertificateAuthority]
/// that form a trust anchor. A
/// [CaPool][google.cloud.security.privateca.v1.CaPool] can be used to manage
/// issuance policies for one or more
/// [CertificateAuthority][google.cloud.security.privateca.v1.CertificateAuthority]
/// resources and to rotate CA certificates in and out of the trust anchor.
///
/// [google.cloud.security.privateca.v1.CaPool]: <doc:CaPool>
/// [google.cloud.security.privateca.v1.CertificateAuthority]: <doc:CertificateAuthority>
public struct CaPool: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name for this
  /// [CaPool][google.cloud.security.privateca.v1.CaPool] in the format
  /// `projects/*/locations/*/caPools/*`.
  ///
  /// [google.cloud.security.privateca.v1.CaPool]: <doc:CaPool>
  public var name: Swift.String = Swift.String()

  /// Required. Immutable. The
  /// [Tier][google.cloud.security.privateca.v1.CaPool.Tier] of this
  /// [CaPool][google.cloud.security.privateca.v1.CaPool].
  ///
  /// [google.cloud.security.privateca.v1.CaPool]: <doc:CaPool>
  /// [google.cloud.security.privateca.v1.CaPool.Tier]: <doc:CaPool/Tier>
  public var tier: CaPool.Tier = CaPool.Tier()

  /// Optional. The
  /// [IssuancePolicy][google.cloud.security.privateca.v1.CaPool.IssuancePolicy]
  /// to control how
  /// [Certificates][google.cloud.security.privateca.v1.Certificate] will be
  /// issued from this [CaPool][google.cloud.security.privateca.v1.CaPool].
  ///
  /// [google.cloud.security.privateca.v1.CaPool]: <doc:CaPool>
  /// [google.cloud.security.privateca.v1.CaPool.IssuancePolicy]: <doc:CaPool/IssuancePolicy>
  /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
  public var issuancePolicy: CaPool.IssuancePolicy? = nil

  /// Optional. The
  /// [PublishingOptions][google.cloud.security.privateca.v1.CaPool.PublishingOptions]
  /// to follow when issuing
  /// [Certificates][google.cloud.security.privateca.v1.Certificate] from any
  /// [CertificateAuthority][google.cloud.security.privateca.v1.CertificateAuthority]
  /// in this [CaPool][google.cloud.security.privateca.v1.CaPool].
  ///
  /// [google.cloud.security.privateca.v1.CaPool]: <doc:CaPool>
  /// [google.cloud.security.privateca.v1.CaPool.PublishingOptions]: <doc:CaPool/PublishingOptions>
  /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
  /// [google.cloud.security.privateca.v1.CertificateAuthority]: <doc:CertificateAuthority>
  public var publishingOptions: CaPool.PublishingOptions? = nil

  /// Optional. When
  /// [EncryptionSpec][google.cloud.security.privateca.v1.EncryptionSpec] is
  /// provided, the [Subject][google.cloud.security.privateca.v1.Subject],
  /// [SubjectAltNames][google.cloud.security.privateca.v1.SubjectAltNames], and
  /// the PEM-encoded certificate fields will be encrypted at rest.
  ///
  /// [google.cloud.security.privateca.v1.EncryptionSpec]: <doc:EncryptionSpec>
  /// [google.cloud.security.privateca.v1.Subject]: <doc:Subject>
  /// [google.cloud.security.privateca.v1.SubjectAltNames]: <doc:SubjectAltNames>
  public var encryptionSpec: EncryptionSpec? = nil

  /// Optional. Labels with user-defined metadata.
  public var labels: [Swift.String: Swift.String] = [:]

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CaPool`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CaPool().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let tier = CodingKeys(stringValue: "tier")
    static let issuancePolicy = CodingKeys(stringValue: "issuancePolicy")
    static let publishingOptions = CodingKeys(stringValue: "publishingOptions")
    static let encryptionSpec = CodingKeys(stringValue: "encryptionSpec")
    static let labels = CodingKeys(stringValue: "labels")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "tier",
      "issuancePolicy",
      "publishingOptions",
      "encryptionSpec",
      "labels",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(CaPool.Tier.self, forKey: .tier) {
      self.tier = value
    }
    self.issuancePolicy = try container.decodeIfPresent(
      CaPool.IssuancePolicy.self, forKey: .issuancePolicy)
    self.publishingOptions = try container.decodeIfPresent(
      CaPool.PublishingOptions.self, forKey: .publishingOptions)
    self.encryptionSpec = try container.decodeIfPresent(
      EncryptionSpec.self, forKey: .encryptionSpec)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.tier, forKey: .tier)
    try container.encodeIfPresent(self.issuancePolicy, forKey: .issuancePolicy)
    try container.encodeIfPresent(self.publishingOptions, forKey: .publishingOptions)
    try container.encodeIfPresent(self.encryptionSpec, forKey: .encryptionSpec)
    try container.encode(self.labels, forKey: .labels)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Options relating to the publication of each
  /// [CertificateAuthority][google.cloud.security.privateca.v1.CertificateAuthority]'s
  /// CA certificate and CRLs and their inclusion as extensions in issued
  /// [Certificates][google.cloud.security.privateca.v1.Certificate]. The options
  /// set here apply to certificates issued by any
  /// [CertificateAuthority][google.cloud.security.privateca.v1.CertificateAuthority]
  /// in the [CaPool][google.cloud.security.privateca.v1.CaPool].
  ///
  /// [google.cloud.security.privateca.v1.CaPool]: <doc:CaPool>
  /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
  /// [google.cloud.security.privateca.v1.CertificateAuthority]: <doc:CertificateAuthority>
  public struct PublishingOptions: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. When true, publishes each
    /// [CertificateAuthority][google.cloud.security.privateca.v1.CertificateAuthority]'s
    /// CA certificate and includes its URL in the "Authority Information Access"
    /// X.509 extension in all issued
    /// [Certificates][google.cloud.security.privateca.v1.Certificate]. If this
    /// is false, the CA certificate will not be published and the corresponding
    /// X.509 extension will not be written in issued certificates.
    ///
    /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
    /// [google.cloud.security.privateca.v1.CertificateAuthority]: <doc:CertificateAuthority>
    public var publishCaCert: Swift.Bool = Swift.Bool()

    /// Optional. When true, publishes each
    /// [CertificateAuthority][google.cloud.security.privateca.v1.CertificateAuthority]'s
    /// CRL and includes its URL in the "CRL Distribution Points" X.509 extension
    /// in all issued
    /// [Certificates][google.cloud.security.privateca.v1.Certificate]. If this
    /// is false, CRLs will not be published and the corresponding X.509
    /// extension will not be written in issued certificates. CRLs will expire 7
    /// days from their creation. However, we will rebuild daily. CRLs are also
    /// rebuilt shortly after a certificate is revoked.
    ///
    /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
    /// [google.cloud.security.privateca.v1.CertificateAuthority]: <doc:CertificateAuthority>
    public var publishCrl: Swift.Bool = Swift.Bool()

    /// Optional. Specifies the encoding format of each
    /// [CertificateAuthority][google.cloud.security.privateca.v1.CertificateAuthority]
    /// resource's CA certificate and CRLs. If this is omitted, CA certificates
    /// and CRLs will be published in PEM.
    ///
    /// [google.cloud.security.privateca.v1.CertificateAuthority]: <doc:CertificateAuthority>
    public var encodingFormat: CaPool.PublishingOptions.EncodingFormat = CaPool.PublishingOptions
      .EncodingFormat()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PublishingOptions`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PublishingOptions().with { $0.publishCaCert = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let publishCaCert = CodingKeys(stringValue: "publishCaCert")
      static let publishCrl = CodingKeys(stringValue: "publishCrl")
      static let encodingFormat = CodingKeys(stringValue: "encodingFormat")

      static let _knownKeys: Set<Swift.String> = [
        "publishCaCert",
        "publishCrl",
        "encodingFormat",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .publishCaCert) {
        self.publishCaCert = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .publishCrl) {
        self.publishCrl = value
      }
      if let value = try container.decodeIfPresent(
        CaPool.PublishingOptions.EncodingFormat.self, forKey: .encodingFormat)
      {
        self.encodingFormat = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.publishCaCert, forKey: .publishCaCert)
      try container.encode(self.publishCrl, forKey: .publishCrl)
      try container.encode(self.encodingFormat, forKey: .encodingFormat)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Supported encoding formats for publishing.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum EncodingFormat: Codable, Equatable, Sendable {
      /// Not specified. By default, PEM format will be used.
      case unspecified
      /// The
      /// [CertificateAuthority][google.cloud.security.privateca.v1.CertificateAuthority]'s
      /// CA certificate and CRLs will be published in PEM format.
      ///
      /// [google.cloud.security.privateca.v1.CertificateAuthority]: <doc:CertificateAuthority>
      case pem
      /// The
      /// [CertificateAuthority][google.cloud.security.privateca.v1.CertificateAuthority]'s
      /// CA certificate and CRLs will be published in DER format.
      ///
      /// [google.cloud.security.privateca.v1.CertificateAuthority]: <doc:CertificateAuthority>
      case der
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .pem: return 1
        case .der: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "ENCODING_FORMAT_UNSPECIFIED"
        case .pem: return "PEM"
        case .der: return "DER"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:EncodingFormat/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "ENCODING_FORMAT_UNSPECIFIED": self = .unspecified
        case "PEM": self = .pem
        case "DER": self = .der
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:EncodingFormat/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .pem
        case 2: self = .der
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("ENCODING_FORMAT_UNSPECIFIED")
        case .pem: return try container.encode("PEM")
        case .der: return try container.encode("DER")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.security.privateca.v1.CaPool.PublishingOptions"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Defines controls over all certificate issuance within a
  /// [CaPool][google.cloud.security.privateca.v1.CaPool].
  ///
  /// [google.cloud.security.privateca.v1.CaPool]: <doc:CaPool>
  public struct IssuancePolicy: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. If any
    /// [AllowedKeyType][google.cloud.security.privateca.v1.CaPool.IssuancePolicy.AllowedKeyType]
    /// is specified, then the certificate request's public key must match one of
    /// the key types listed here. Otherwise, any key may be used.
    ///
    /// [google.cloud.security.privateca.v1.CaPool.IssuancePolicy.AllowedKeyType]: <doc:CaPool/IssuancePolicy/AllowedKeyType>
    public var allowedKeyTypes: [CaPool.IssuancePolicy.AllowedKeyType] = []

    /// Optional. If set, all certificates issued from this
    /// [CaPool][google.cloud.security.privateca.v1.CaPool] will be backdated by
    /// this duration. The 'not_before_time' will be the issuance time minus this
    /// [backdate_duration][google.cloud.security.privateca.v1.CaPool.IssuancePolicy.backdate_duration],
    /// and the 'not_after_time' will be adjusted to preserve the requested
    /// lifetime. The maximum duration that a certificate can be backdated with
    /// these options is 48 hours in the past.
    /// This option cannot be set if
    /// [allow_requester_specified_not_before_time][google.cloud.security.privateca.v1.CaPool.IssuancePolicy.allow_requester_specified_not_before_time]
    /// is set.
    ///
    /// [google.cloud.security.privateca.v1.CaPool]: <doc:CaPool>
    /// [google.cloud.security.privateca.v1.CaPool.IssuancePolicy.allow_requester_specified_not_before_time]: <doc:CaPool/IssuancePolicy/allowRequesterSpecifiedNotBeforeTime>
    /// [google.cloud.security.privateca.v1.CaPool.IssuancePolicy.backdate_duration]: <doc:CaPool/IssuancePolicy/backdateDuration>
    public var backdateDuration: GoogleWKT.Duration? = nil

    /// Optional. If set to true, allows requesters to specify the
    /// [requested_not_before_time][google.cloud.security.privateca.v1.Certificate.requested_not_before_time]
    /// field when creating a
    /// [Certificate][google.cloud.security.privateca.v1.Certificate].
    /// Certificates requested with this option enabled will have a
    /// 'not_before_time' equal to the value specified in the request. The
    /// 'not_after_time' will be adjusted to preserve the requested lifetime. The
    /// maximum time that a certificate can be backdated with these options is 48
    /// hours in the past. This option cannot be set if
    /// [backdate_duration][google.cloud.security.privateca.v1.CaPool.IssuancePolicy.backdate_duration]
    /// is set.
    ///
    /// [google.cloud.security.privateca.v1.CaPool.IssuancePolicy.backdate_duration]: <doc:CaPool/IssuancePolicy/backdateDuration>
    /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
    /// [google.cloud.security.privateca.v1.Certificate.requested_not_before_time]: <doc:Certificate/requestedNotBeforeTime>
    public var allowRequesterSpecifiedNotBeforeTime: Swift.Bool = Swift.Bool()

    /// Optional. The maximum lifetime allowed for issued
    /// [Certificates][google.cloud.security.privateca.v1.Certificate]. Note that
    /// if the issuing
    /// [CertificateAuthority][google.cloud.security.privateca.v1.CertificateAuthority]
    /// expires before a
    /// [Certificate][google.cloud.security.privateca.v1.Certificate] resource's
    /// requested maximum_lifetime, the effective lifetime will be explicitly
    /// truncated to match it.
    ///
    /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
    /// [google.cloud.security.privateca.v1.CertificateAuthority]: <doc:CertificateAuthority>
    public var maximumLifetime: GoogleWKT.Duration? = nil

    /// Optional. If specified, then only methods allowed in the
    /// [IssuanceModes][google.cloud.security.privateca.v1.CaPool.IssuancePolicy.IssuanceModes]
    /// may be used to issue
    /// [Certificates][google.cloud.security.privateca.v1.Certificate].
    ///
    /// [google.cloud.security.privateca.v1.CaPool.IssuancePolicy.IssuanceModes]: <doc:CaPool/IssuancePolicy/IssuanceModes>
    /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
    public var allowedIssuanceModes: CaPool.IssuancePolicy.IssuanceModes? = nil

    /// Optional. A set of X.509 values that will be applied to all certificates
    /// issued through this [CaPool][google.cloud.security.privateca.v1.CaPool].
    /// If a certificate request includes conflicting values for the same
    /// properties, they will be overwritten by the values defined here. If a
    /// certificate request uses a
    /// [CertificateTemplate][google.cloud.security.privateca.v1.CertificateTemplate]
    /// that defines conflicting
    /// [predefined_values][google.cloud.security.privateca.v1.CertificateTemplate.predefined_values]
    /// for the same properties, the certificate issuance request will fail.
    ///
    /// [google.cloud.security.privateca.v1.CaPool]: <doc:CaPool>
    /// [google.cloud.security.privateca.v1.CertificateTemplate]: <doc:CertificateTemplate>
    /// [google.cloud.security.privateca.v1.CertificateTemplate.predefined_values]: <doc:CertificateTemplate/predefinedValues>
    public var baselineValues: X509Parameters? = nil

    /// Optional. Describes constraints on identities that may appear in
    /// [Certificates][google.cloud.security.privateca.v1.Certificate] issued
    /// through this [CaPool][google.cloud.security.privateca.v1.CaPool]. If this
    /// is omitted, then this [CaPool][google.cloud.security.privateca.v1.CaPool]
    /// will not add restrictions on a certificate's identity.
    ///
    /// [google.cloud.security.privateca.v1.CaPool]: <doc:CaPool>
    /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
    public var identityConstraints: CertificateIdentityConstraints? = nil

    /// Optional. Describes the set of X.509 extensions that may appear in a
    /// [Certificate][google.cloud.security.privateca.v1.Certificate] issued
    /// through this [CaPool][google.cloud.security.privateca.v1.CaPool]. If a
    /// certificate request sets extensions that don't appear in the
    /// [passthrough_extensions][google.cloud.security.privateca.v1.CaPool.IssuancePolicy.passthrough_extensions],
    /// those extensions will be dropped. If a certificate request uses a
    /// [CertificateTemplate][google.cloud.security.privateca.v1.CertificateTemplate]
    /// with
    /// [predefined_values][google.cloud.security.privateca.v1.CertificateTemplate.predefined_values]
    /// that don't appear here, the certificate issuance request will fail. If
    /// this is omitted, then this
    /// [CaPool][google.cloud.security.privateca.v1.CaPool] will not add
    /// restrictions on a certificate's X.509 extensions. These constraints do
    /// not apply to X.509 extensions set in this
    /// [CaPool][google.cloud.security.privateca.v1.CaPool]'s
    /// [baseline_values][google.cloud.security.privateca.v1.CaPool.IssuancePolicy.baseline_values].
    ///
    /// [google.cloud.security.privateca.v1.CaPool]: <doc:CaPool>
    /// [google.cloud.security.privateca.v1.CaPool.IssuancePolicy.baseline_values]: <doc:CaPool/IssuancePolicy/baselineValues>
    /// [google.cloud.security.privateca.v1.CaPool.IssuancePolicy.passthrough_extensions]: <doc:CaPool/IssuancePolicy/passthroughExtensions>
    /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
    /// [google.cloud.security.privateca.v1.CertificateTemplate]: <doc:CertificateTemplate>
    /// [google.cloud.security.privateca.v1.CertificateTemplate.predefined_values]: <doc:CertificateTemplate/predefinedValues>
    public var passthroughExtensions: CertificateExtensionConstraints? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `IssuancePolicy`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = IssuancePolicy().with { $0.allowedKeyTypes = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let allowedKeyTypes = CodingKeys(stringValue: "allowedKeyTypes")
      static let backdateDuration = CodingKeys(stringValue: "backdateDuration")
      static let allowRequesterSpecifiedNotBeforeTime = CodingKeys(
        stringValue: "allowRequesterSpecifiedNotBeforeTime")
      static let maximumLifetime = CodingKeys(stringValue: "maximumLifetime")
      static let allowedIssuanceModes = CodingKeys(stringValue: "allowedIssuanceModes")
      static let baselineValues = CodingKeys(stringValue: "baselineValues")
      static let identityConstraints = CodingKeys(stringValue: "identityConstraints")
      static let passthroughExtensions = CodingKeys(stringValue: "passthroughExtensions")

      static let _knownKeys: Set<Swift.String> = [
        "allowedKeyTypes",
        "backdateDuration",
        "allowRequesterSpecifiedNotBeforeTime",
        "maximumLifetime",
        "allowedIssuanceModes",
        "baselineValues",
        "identityConstraints",
        "passthroughExtensions",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        [CaPool.IssuancePolicy.AllowedKeyType].self, forKey: .allowedKeyTypes)
      {
        self.allowedKeyTypes = value
      }
      self.backdateDuration = try container.decodeIfPresent(
        GoogleWKT.Duration.self, forKey: .backdateDuration)
      if let value = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .allowRequesterSpecifiedNotBeforeTime)
      {
        self.allowRequesterSpecifiedNotBeforeTime = value
      }
      self.maximumLifetime = try container.decodeIfPresent(
        GoogleWKT.Duration.self, forKey: .maximumLifetime)
      self.allowedIssuanceModes = try container.decodeIfPresent(
        CaPool.IssuancePolicy.IssuanceModes.self, forKey: .allowedIssuanceModes)
      self.baselineValues = try container.decodeIfPresent(
        X509Parameters.self, forKey: .baselineValues)
      self.identityConstraints = try container.decodeIfPresent(
        CertificateIdentityConstraints.self, forKey: .identityConstraints)
      self.passthroughExtensions = try container.decodeIfPresent(
        CertificateExtensionConstraints.self, forKey: .passthroughExtensions)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.allowedKeyTypes, forKey: .allowedKeyTypes)
      try container.encodeIfPresent(self.backdateDuration, forKey: .backdateDuration)
      try container.encode(
        self.allowRequesterSpecifiedNotBeforeTime, forKey: .allowRequesterSpecifiedNotBeforeTime)
      try container.encodeIfPresent(self.maximumLifetime, forKey: .maximumLifetime)
      try container.encodeIfPresent(self.allowedIssuanceModes, forKey: .allowedIssuanceModes)
      try container.encodeIfPresent(self.baselineValues, forKey: .baselineValues)
      try container.encodeIfPresent(self.identityConstraints, forKey: .identityConstraints)
      try container.encodeIfPresent(self.passthroughExtensions, forKey: .passthroughExtensions)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Describes a "type" of key that may be used in a
    /// [Certificate][google.cloud.security.privateca.v1.Certificate] issued from
    /// a [CaPool][google.cloud.security.privateca.v1.CaPool]. Note that a single
    /// [AllowedKeyType][google.cloud.security.privateca.v1.CaPool.IssuancePolicy.AllowedKeyType]
    /// may refer to either a fully-qualified key algorithm, such as RSA 4096, or
    /// a family of key algorithms, such as any RSA key.
    ///
    /// [google.cloud.security.privateca.v1.CaPool]: <doc:CaPool>
    /// [google.cloud.security.privateca.v1.CaPool.IssuancePolicy.AllowedKeyType]: <doc:CaPool/IssuancePolicy/AllowedKeyType>
    /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
    public struct AllowedKeyType: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      public var keyType: OneOf_KeyType? = nil

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `AllowedKeyType`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = AllowedKeyType().with { $0.rsa = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let rsa = CodingKeys(stringValue: "rsa")
        static let ellipticCurve = CodingKeys(stringValue: "ellipticCurve")

        static let _knownKeys: Set<Swift.String> = [
          "rsa",
          "ellipticCurve",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        var keyType: OneOf_KeyType? = nil
        let keyTypeCheckAndSet = {
          if keyType != nil {
            throw DecodingError.dataCorrupted(
              DecodingError.Context(
                codingPath: decoder.codingPath,
                debugDescription: "Multiple values set for oneof 'keyType'"))
          }
          keyType = $0
        }
        if let rsa = try container.decodeIfPresent(
          CaPool.IssuancePolicy.AllowedKeyType.RsaKeyType?.self, forKey: .rsa)
        {
          try keyTypeCheckAndSet(.rsa(rsa))
        }
        if let ellipticCurve = try container.decodeIfPresent(
          CaPool.IssuancePolicy.AllowedKeyType.EcKeyType?.self, forKey: .ellipticCurve)
        {
          try keyTypeCheckAndSet(.ellipticCurve(ellipticCurve))
        }
        self.keyType = keyType
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.Value.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        if let choice = self.keyType {
          switch choice {
          case .rsa(let value):
            try container.encode(value, forKey: .rsa)
          case .ellipticCurve(let value):
            try container.encode(value, forKey: .ellipticCurve)
          }
        }
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      /// Describes an RSA key that may be used in a
      /// [Certificate][google.cloud.security.privateca.v1.Certificate] issued
      /// from a [CaPool][google.cloud.security.privateca.v1.CaPool].
      ///
      /// [google.cloud.security.privateca.v1.CaPool]: <doc:CaPool>
      /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
      public struct RsaKeyType: Codable, Equatable, GoogleWKT._AnyPackable,
        Sendable
      {
        /// Optional. The minimum allowed RSA modulus size (inclusive), in bits.
        /// If this is not set, or if set to zero, the service-level min RSA
        /// modulus size will continue to apply.
        public var minModulusSize: Swift.Int64 = Swift.Int64()

        /// Optional. The maximum allowed RSA modulus size (inclusive), in bits.
        /// If this is not set, or if set to zero, the service will not enforce
        /// an explicit upper bound on RSA modulus sizes.
        public var maxModulusSize: Swift.Int64 = Swift.Int64()

        @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

        /// Initialize a new instance of `RsaKeyType`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = RsaKeyType().with { $0.minModulusSize = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        private struct CodingKeys: CodingKey {
          var stringValue: Swift.String
          var intValue: Swift.Int? { nil }
          init(stringValue: Swift.String) { self.stringValue = stringValue }
          init?(intValue: Swift.Int) { nil }

          static let minModulusSize = CodingKeys(stringValue: "minModulusSize")
          static let maxModulusSize = CodingKeys(stringValue: "maxModulusSize")

          static let _knownKeys: Set<Swift.String> = [
            "minModulusSize",
            "maxModulusSize",
          ]
        }

        public init(from decoder: Decoder) throws {
          let container = try decoder.container(keyedBy: CodingKeys.self)
          if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .minModulusSize) {
            self.minModulusSize = value
          }
          if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .maxModulusSize) {
            self.maxModulusSize = value
          }
          for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
            self._unknownFields.json[key.stringValue] = try container.decode(
              GoogleWKT.Value.self, forKey: key)
          }
        }

        public func encode(to encoder: Encoder) throws {
          var container = encoder.container(keyedBy: CodingKeys.self)
          try container.encode(self.minModulusSize, forKey: .minModulusSize)
          try container.encode(self.maxModulusSize, forKey: .maxModulusSize)
          for (key, value) in self._unknownFields.json {
            try container.encode(value, forKey: CodingKeys(stringValue: key))
          }
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.security.privateca.v1.CaPool.IssuancePolicy.AllowedKeyType.RsaKeyType"
        }
        public init(fromAny any: GoogleWKT.`Any`) throws {
          self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleWKT.Struct {
          return try GoogleWKT._slowAnySerialize(message: self)
        }
      }

      /// Describes an Elliptic Curve key that may be used in a
      /// [Certificate][google.cloud.security.privateca.v1.Certificate] issued
      /// from a [CaPool][google.cloud.security.privateca.v1.CaPool].
      ///
      /// [google.cloud.security.privateca.v1.CaPool]: <doc:CaPool>
      /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
      public struct EcKeyType: Codable, Equatable, GoogleWKT._AnyPackable,
        Sendable
      {
        /// Optional. A signature algorithm that must be used. If this is
        /// omitted, any EC-based signature algorithm will be allowed.
        public var signatureAlgorithm:
          CaPool.IssuancePolicy.AllowedKeyType.EcKeyType.EcSignatureAlgorithm = CaPool
            .IssuancePolicy.AllowedKeyType.EcKeyType.EcSignatureAlgorithm()

        @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

        /// Initialize a new instance of `EcKeyType`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = EcKeyType().with { $0.signatureAlgorithm = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        private struct CodingKeys: CodingKey {
          var stringValue: Swift.String
          var intValue: Swift.Int? { nil }
          init(stringValue: Swift.String) { self.stringValue = stringValue }
          init?(intValue: Swift.Int) { nil }

          static let signatureAlgorithm = CodingKeys(stringValue: "signatureAlgorithm")

          static let _knownKeys: Set<Swift.String> = [
            "signatureAlgorithm"
          ]
        }

        public init(from decoder: Decoder) throws {
          let container = try decoder.container(keyedBy: CodingKeys.self)
          if let value = try container.decodeIfPresent(
            CaPool.IssuancePolicy.AllowedKeyType.EcKeyType.EcSignatureAlgorithm.self,
            forKey: .signatureAlgorithm)
          {
            self.signatureAlgorithm = value
          }
          for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
            self._unknownFields.json[key.stringValue] = try container.decode(
              GoogleWKT.Value.self, forKey: key)
          }
        }

        public func encode(to encoder: Encoder) throws {
          var container = encoder.container(keyedBy: CodingKeys.self)
          try container.encode(self.signatureAlgorithm, forKey: .signatureAlgorithm)
          for (key, value) in self._unknownFields.json {
            try container.encode(value, forKey: CodingKeys(stringValue: key))
          }
        }

        /// Describes an elliptic curve-based signature algorithm that may be
        /// used in a
        /// [Certificate][google.cloud.security.privateca.v1.Certificate] issued
        /// from a [CaPool][google.cloud.security.privateca.v1.CaPool].
        ///
        /// [google.cloud.security.privateca.v1.CaPool]: <doc:CaPool>
        /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
        ///
        /// - Note: Adding cases to this enumeration is not considered a breaking change.
        ///   Always include an `@unknown default:` case when switching over this type.
        ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
        ///   expecting specific values to remain unparsed; future releases may promote
        ///   them to named cases.
        public enum EcSignatureAlgorithm: Codable, Equatable, Sendable {
          /// Not specified. Signifies that any signature algorithm may be used.
          case unspecified
          /// Refers to the Elliptic Curve Digital Signature Algorithm over the
          /// NIST P-256 curve.
          case ecdsaP256
          /// Refers to the Elliptic Curve Digital Signature Algorithm over the
          /// NIST P-384 curve.
          case ecdsaP384
          /// Refers to the Edwards-curve Digital Signature Algorithm over curve
          /// 25519, as described in RFC 8410.
          case eddsa25519
          /// Encodes an unknown integer value.
          ///
          /// The most common cause for an unknown value is for the service to send
          /// a value unknown to the library. We recommend you update your library to
          /// the latest version.
          ///
          /// - Warning: Do not pattern-match specific integer values in this case;
          ///   future releases may promote them to named enum cases.
          case unknownIntValue(Int)
          /// Encodes an unknown string value.
          ///
          /// The most common cause for an unknown value is for the service to send
          /// a value unknown to the library. We recommend you update your library to
          /// the latest version.
          ///
          /// - Warning: Do not pattern-match specific string literals in this case;
          ///   future releases may promote them to named enum cases.
          case unknownStringValue(String)

          public init() {
            self = .unspecified
          }

          /// Returns the integer value associated with the enumeration.
          ///
          /// If the enumeration was initialized with an unknown string value, this returns `nil`.
          public var intValue: Int? {
            switch self {
            case .unspecified: return 0
            case .ecdsaP256: return 1
            case .ecdsaP384: return 2
            case .eddsa25519: return 3
            case .unknownIntValue(let v): return v
            case .unknownStringValue: return nil
            }
          }

          /// Returns the string value (or name) associated with the enumeration.
          ///
          /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
          public var stringValue: Swift.String? {
            switch self {
            case .unspecified: return "EC_SIGNATURE_ALGORITHM_UNSPECIFIED"
            case .ecdsaP256: return "ECDSA_P256"
            case .ecdsaP384: return "ECDSA_P384"
            case .eddsa25519: return "EDDSA_25519"
            case .unknownIntValue: return nil
            case .unknownStringValue(let v): return v
            }
          }

          /// Initialize from a string value.
          ///
          /// If the value is unknown, this initializes to [`unknownStringValue`](doc:EcSignatureAlgorithm/unknownStringValue(_:)).
          public init(stringValue: Swift.String) {
            switch stringValue {
            case "EC_SIGNATURE_ALGORITHM_UNSPECIFIED": self = .unspecified
            case "ECDSA_P256": self = .ecdsaP256
            case "ECDSA_P384": self = .ecdsaP384
            case "EDDSA_25519": self = .eddsa25519
            default: self = .unknownStringValue(stringValue)
            }
          }

          /// Initialize from an integer value.
          ///
          /// If the value is unknown, this initializes to [`unknownIntValue`](doc:EcSignatureAlgorithm/unknownIntValue(_:)).
          public init(intValue: Int) {
            switch intValue {
            case 0: self = .unspecified
            case 1: self = .ecdsaP256
            case 2: self = .ecdsaP384
            case 3: self = .eddsa25519
            default: self = .unknownIntValue(intValue)
            }
          }

          public init(from decoder: Decoder) throws {
            let container = try decoder.singleValueContainer()
            if let v = try? container.decode(Int.self) {
              self.init(intValue: v)
              return
            }
            if let s = try? container.decode(String.self) {
              if let v = Int(s) {
                self.init(intValue: v)
              } else {
                self.init(stringValue: s)
              }
              return
            }
            throw DecodingError.dataCorruptedError(
              in: container, debugDescription: "Expected enum value, must be integer or string.")
          }

          public func encode(to encoder: Encoder) throws {
            var container = encoder.singleValueContainer()
            switch self {
            case .unspecified: return try container.encode("EC_SIGNATURE_ALGORITHM_UNSPECIFIED")
            case .ecdsaP256: return try container.encode("ECDSA_P256")
            case .ecdsaP384: return try container.encode("ECDSA_P384")
            case .eddsa25519: return try container.encode("EDDSA_25519")
            case .unknownIntValue(let v): return try container.encode(v)
            case .unknownStringValue(let v): return try container.encode(v)
            }
          }
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.security.privateca.v1.CaPool.IssuancePolicy.AllowedKeyType.EcKeyType"
        }
        public init(fromAny any: GoogleWKT.`Any`) throws {
          self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleWKT.Struct {
          return try GoogleWKT._slowAnySerialize(message: self)
        }
      }

      public enum OneOf_KeyType: Codable, Equatable, Sendable {
        /// Represents an allowed RSA key type.
        indirect case rsa(CaPool.IssuancePolicy.AllowedKeyType.RsaKeyType?)
        /// Represents an allowed Elliptic Curve key type.
        indirect case ellipticCurve(CaPool.IssuancePolicy.AllowedKeyType.EcKeyType?)
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.security.privateca.v1.CaPool.IssuancePolicy.AllowedKeyType"
      }
      public init(fromAny any: GoogleWKT.`Any`) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.Struct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// [IssuanceModes][google.cloud.security.privateca.v1.CaPool.IssuancePolicy.IssuanceModes]
    /// specifies the allowed ways in which
    /// [Certificates][google.cloud.security.privateca.v1.Certificate] may be
    /// requested from this [CaPool][google.cloud.security.privateca.v1.CaPool].
    ///
    /// [google.cloud.security.privateca.v1.CaPool]: <doc:CaPool>
    /// [google.cloud.security.privateca.v1.CaPool.IssuancePolicy.IssuanceModes]: <doc:CaPool/IssuancePolicy/IssuanceModes>
    /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
    public struct IssuanceModes: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Optional. When true, allows callers to create
      /// [Certificates][google.cloud.security.privateca.v1.Certificate] by
      /// specifying a CSR.
      ///
      /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
      public var allowCsrBasedIssuance: Swift.Bool = Swift.Bool()

      /// Optional. When true, allows callers to create
      /// [Certificates][google.cloud.security.privateca.v1.Certificate] by
      /// specifying a
      /// [CertificateConfig][google.cloud.security.privateca.v1.CertificateConfig].
      ///
      /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
      /// [google.cloud.security.privateca.v1.CertificateConfig]: <doc:CertificateConfig>
      public var allowConfigBasedIssuance: Swift.Bool = Swift.Bool()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `IssuanceModes`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = IssuanceModes().with { $0.allowCsrBasedIssuance = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let allowCsrBasedIssuance = CodingKeys(stringValue: "allowCsrBasedIssuance")
        static let allowConfigBasedIssuance = CodingKeys(stringValue: "allowConfigBasedIssuance")

        static let _knownKeys: Set<Swift.String> = [
          "allowCsrBasedIssuance",
          "allowConfigBasedIssuance",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(
          Swift.Bool.self, forKey: .allowCsrBasedIssuance)
        {
          self.allowCsrBasedIssuance = value
        }
        if let value = try container.decodeIfPresent(
          Swift.Bool.self, forKey: .allowConfigBasedIssuance)
        {
          self.allowConfigBasedIssuance = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.Value.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.allowCsrBasedIssuance, forKey: .allowCsrBasedIssuance)
        try container.encode(self.allowConfigBasedIssuance, forKey: .allowConfigBasedIssuance)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.security.privateca.v1.CaPool.IssuancePolicy.IssuanceModes"
      }
      public init(fromAny any: GoogleWKT.`Any`) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.Struct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.security.privateca.v1.CaPool.IssuancePolicy"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The tier of a [CaPool][google.cloud.security.privateca.v1.CaPool],
  /// indicating its supported functionality and/or billing SKU.
  ///
  /// [google.cloud.security.privateca.v1.CaPool]: <doc:CaPool>
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Tier: Codable, Equatable, Sendable {
    /// Not specified.
    case unspecified
    /// Enterprise tier.
    case enterprise
    /// DevOps tier.
    case devops
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .enterprise: return 1
      case .devops: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TIER_UNSPECIFIED"
      case .enterprise: return "ENTERPRISE"
      case .devops: return "DEVOPS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Tier/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TIER_UNSPECIFIED": self = .unspecified
      case "ENTERPRISE": self = .enterprise
      case "DEVOPS": self = .devops
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Tier/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .enterprise
      case 2: self = .devops
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("TIER_UNSPECIFIED")
      case .enterprise: return try container.encode("ENTERPRISE")
      case .devops: return try container.encode("DEVOPS")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.security.privateca.v1.CaPool"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
