// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// A [Certificate][google.cloud.security.privateca.v1.Certificate] corresponds
/// to a signed X.509 certificate issued by a
/// [CertificateAuthority][google.cloud.security.privateca.v1.CertificateAuthority].
///
/// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
/// [google.cloud.security.privateca.v1.CertificateAuthority]: <doc:CertificateAuthority>
public struct Certificate: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name for this
  /// [Certificate][google.cloud.security.privateca.v1.Certificate] in the format
  /// `projects/*/locations/*/caPools/*/certificates/*`.
  ///
  /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
  public var name: Swift.String = Swift.String()

  /// Output only. The resource name of the issuing
  /// [CertificateAuthority][google.cloud.security.privateca.v1.CertificateAuthority]
  /// in the format `projects/*/locations/*/caPools/*/certificateAuthorities/*`.
  ///
  /// [google.cloud.security.privateca.v1.CertificateAuthority]: <doc:CertificateAuthority>
  public var issuerCertificateAuthority: Swift.String = Swift.String()

  /// Required. Immutable. The desired lifetime of a certificate. Used to create
  /// the "not_before_time" and "not_after_time" fields inside an X.509
  /// certificate. Note that the lifetime may be truncated if it would extend
  /// past the life of any certificate authority in the issuing chain.
  public var lifetime: GoogleWKT.Duration? = nil

  /// Immutable. The resource name for a
  /// [CertificateTemplate][google.cloud.security.privateca.v1.CertificateTemplate]
  /// used to issue this certificate, in the format
  /// `projects/*/locations/*/certificateTemplates/*`.
  /// If this is specified, the caller must have the necessary permission to
  /// use this template. If this is omitted, no template will be used.
  /// This template must be in the same location as the
  /// [Certificate][google.cloud.security.privateca.v1.Certificate].
  ///
  /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
  /// [google.cloud.security.privateca.v1.CertificateTemplate]: <doc:CertificateTemplate>
  public var certificateTemplate: Swift.String = Swift.String()

  /// Immutable. Specifies how the
  /// [Certificate][google.cloud.security.privateca.v1.Certificate]'s identity
  /// fields are to be decided. If this is omitted, the `DEFAULT` subject mode
  /// will be used.
  ///
  /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
  public var subjectMode: SubjectRequestMode = SubjectRequestMode()

  /// Output only. Details regarding the revocation of this
  /// [Certificate][google.cloud.security.privateca.v1.Certificate]. This
  /// [Certificate][google.cloud.security.privateca.v1.Certificate] is considered
  /// revoked if and only if this field is present.
  ///
  /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
  public var revocationDetails: Certificate.RevocationDetails? = nil

  /// Output only. The pem-encoded, signed X.509 certificate.
  public var pemCertificate: Swift.String = Swift.String()

  /// Output only. A structured description of the issued X.509 certificate.
  public var certificateDescription: CertificateDescription? = nil

  /// Output only. The chain that may be used to verify the X.509 certificate.
  /// Expected to be in issuer-to-root order according to RFC 5246.
  public var pemCertificateChain: [Swift.String] = []

  /// Output only. The time at which this
  /// [Certificate][google.cloud.security.privateca.v1.Certificate] was created.
  ///
  /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. The time at which this
  /// [Certificate][google.cloud.security.privateca.v1.Certificate] was updated.
  ///
  /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Optional. Labels with user-defined metadata.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. The requested
  /// [not_before_time][google.cloud.security.privateca.v1.CertificateDescription.SubjectDescription.not_before_time]
  /// of this [Certificate][google.cloud.security.privateca.v1.Certificate]. This
  /// field may only be set if the
  /// [CaPool.IssuancePolicy.allow_requester_specified_not_before_time][google.cloud.security.privateca.v1.CaPool.IssuancePolicy.allow_requester_specified_not_before_time]
  /// field is set to true for the issuing
  /// [CaPool][google.cloud.security.privateca.v1.CaPool].
  ///
  /// If this field is specified, the certificate will be issued with this
  /// 'not_before_time'. If this is not specified, the 'not_before_time' will be
  /// set to the issuance time or issuance time minus
  /// [backdate_duration][google.cloud.security.privateca.v1.CaPool.IssuancePolicy.backdate_duration]
  /// depending on the [CaPool][google.cloud.security.privateca.v1.CaPool]
  /// configuration.
  ///
  /// [google.cloud.security.privateca.v1.CaPool]: <doc:CaPool>
  /// [google.cloud.security.privateca.v1.CaPool.IssuancePolicy.allow_requester_specified_not_before_time]: <doc:CaPool/IssuancePolicy/allowRequesterSpecifiedNotBeforeTime>
  /// [google.cloud.security.privateca.v1.CaPool.IssuancePolicy.backdate_duration]: <doc:CaPool/IssuancePolicy/backdateDuration>
  /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
  /// [google.cloud.security.privateca.v1.CertificateDescription.SubjectDescription.not_before_time]: <doc:CertificateDescription/SubjectDescription/notBeforeTime>
  public var requestedNotBeforeTime: GoogleWKT.Timestamp? = nil

  /// The config used to create a signed X.509 certificate.
  public var certificateConfig: OneOf_CertificateConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Certificate`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Certificate().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let pemCsr = CodingKeys(stringValue: "pemCsr")
    static let config = CodingKeys(stringValue: "config")
    static let issuerCertificateAuthority = CodingKeys(stringValue: "issuerCertificateAuthority")
    static let lifetime = CodingKeys(stringValue: "lifetime")
    static let certificateTemplate = CodingKeys(stringValue: "certificateTemplate")
    static let subjectMode = CodingKeys(stringValue: "subjectMode")
    static let revocationDetails = CodingKeys(stringValue: "revocationDetails")
    static let pemCertificate = CodingKeys(stringValue: "pemCertificate")
    static let certificateDescription = CodingKeys(stringValue: "certificateDescription")
    static let pemCertificateChain = CodingKeys(stringValue: "pemCertificateChain")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let requestedNotBeforeTime = CodingKeys(stringValue: "requestedNotBeforeTime")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "pemCsr",
      "config",
      "issuerCertificateAuthority",
      "lifetime",
      "certificateTemplate",
      "subjectMode",
      "revocationDetails",
      "pemCertificate",
      "certificateDescription",
      "pemCertificateChain",
      "createTime",
      "updateTime",
      "labels",
      "requestedNotBeforeTime",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .issuerCertificateAuthority)
    {
      self.issuerCertificateAuthority = value
    }
    self.lifetime = try container.decodeIfPresent(GoogleWKT.Duration.self, forKey: .lifetime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .certificateTemplate) {
      self.certificateTemplate = value
    }
    if let value = try container.decodeIfPresent(SubjectRequestMode.self, forKey: .subjectMode) {
      self.subjectMode = value
    }
    self.revocationDetails = try container.decodeIfPresent(
      Certificate.RevocationDetails.self, forKey: .revocationDetails)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pemCertificate) {
      self.pemCertificate = value
    }
    self.certificateDescription = try container.decodeIfPresent(
      CertificateDescription.self, forKey: .certificateDescription)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .pemCertificateChain)
    {
      self.pemCertificateChain = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    self.requestedNotBeforeTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .requestedNotBeforeTime)

    var certificateConfig: OneOf_CertificateConfig? = nil
    let certificateConfigCheckAndSet = {
      if certificateConfig != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'certificateConfig'"))
      }
      certificateConfig = $0
    }
    if let pemCsr = try container.decodeIfPresent(Swift.String.self, forKey: .pemCsr) {
      try certificateConfigCheckAndSet(.pemCsr(pemCsr))
    }
    if let config = try container.decodeIfPresent(CertificateConfig?.self, forKey: .config) {
      try certificateConfigCheckAndSet(.config(config))
    }
    self.certificateConfig = certificateConfig
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.issuerCertificateAuthority, forKey: .issuerCertificateAuthority)
    try container.encodeIfPresent(self.lifetime, forKey: .lifetime)
    try container.encode(self.certificateTemplate, forKey: .certificateTemplate)
    try container.encode(self.subjectMode, forKey: .subjectMode)
    try container.encodeIfPresent(self.revocationDetails, forKey: .revocationDetails)
    try container.encode(self.pemCertificate, forKey: .pemCertificate)
    try container.encodeIfPresent(self.certificateDescription, forKey: .certificateDescription)
    try container.encode(self.pemCertificateChain, forKey: .pemCertificateChain)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encodeIfPresent(self.requestedNotBeforeTime, forKey: .requestedNotBeforeTime)

    if let choice = self.certificateConfig {
      switch choice {
      case .pemCsr(let value):
        try container.encode(value, forKey: .pemCsr)
      case .config(let value):
        try container.encode(value, forKey: .config)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Describes fields that are relavent to the revocation of a
  /// [Certificate][google.cloud.security.privateca.v1.Certificate].
  ///
  /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
  public struct RevocationDetails: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Indicates why a
    /// [Certificate][google.cloud.security.privateca.v1.Certificate] was
    /// revoked.
    ///
    /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
    public var revocationState: RevocationReason = RevocationReason()

    /// The time at which this
    /// [Certificate][google.cloud.security.privateca.v1.Certificate] was
    /// revoked.
    ///
    /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
    public var revocationTime: GoogleWKT.Timestamp? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `RevocationDetails`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RevocationDetails().with { $0.revocationState = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let revocationState = CodingKeys(stringValue: "revocationState")
      static let revocationTime = CodingKeys(stringValue: "revocationTime")

      static let _knownKeys: Set<Swift.String> = [
        "revocationState",
        "revocationTime",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(RevocationReason.self, forKey: .revocationState)
      {
        self.revocationState = value
      }
      self.revocationTime = try container.decodeIfPresent(
        GoogleWKT.Timestamp.self, forKey: .revocationTime)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.revocationState, forKey: .revocationState)
      try container.encodeIfPresent(self.revocationTime, forKey: .revocationTime)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.security.privateca.v1.Certificate.RevocationDetails"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The config used to create a signed X.509 certificate.
  public enum OneOf_CertificateConfig: Codable, Equatable, Sendable {
    /// Immutable. A pem-encoded X.509 certificate signing request (CSR).
    case pemCsr(Swift.String)
    /// Immutable. A description of the certificate and key that does not require
    /// X.509 or ASN.1.
    indirect case config(CertificateConfig?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.security.privateca.v1.Certificate"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
