// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A [CertificateConfig][google.cloud.security.privateca.v1.CertificateConfig]
/// describes an X.509 certificate or CSR that is to be created, as an
/// alternative to using ASN.1.
///
/// [google.cloud.security.privateca.v1.CertificateConfig]: <doc:CertificateConfig>
public struct CertificateConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Specifies some of the values in a certificate that are related to
  /// the subject.
  public var subjectConfig: CertificateConfig.SubjectConfig? = nil

  /// Required. Describes how some of the technical X.509 fields in a certificate
  /// should be populated.
  public var x509Config: X509Parameters? = nil

  /// Optional. The public key that corresponds to this config. This is, for
  /// example, used when issuing
  /// [Certificates][google.cloud.security.privateca.v1.Certificate], but not
  /// when creating a self-signed
  /// [CertificateAuthority][google.cloud.security.privateca.v1.CertificateAuthority]
  /// or
  /// [CertificateAuthority][google.cloud.security.privateca.v1.CertificateAuthority]
  /// CSR.
  ///
  /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
  /// [google.cloud.security.privateca.v1.CertificateAuthority]: <doc:CertificateAuthority>
  public var publicKey: PublicKey? = nil

  /// Optional. When specified this provides a custom SKI to be used in the
  /// certificate. This should only be used to maintain a SKI of an existing CA
  /// originally created outside CA service, which was not generated using method
  /// (1) described in RFC 5280 section 4.2.1.2.
  public var subjectKeyId: CertificateConfig.KeyId? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `CertificateConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CertificateConfig().with { $0.subjectConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let subjectConfig = CodingKeys(stringValue: "subjectConfig")
    static let x509Config = CodingKeys(stringValue: "x509Config")
    static let publicKey = CodingKeys(stringValue: "publicKey")
    static let subjectKeyId = CodingKeys(stringValue: "subjectKeyId")

    static let _knownKeys: Set<Swift.String> = [
      "subjectConfig",
      "x509Config",
      "publicKey",
      "subjectKeyId",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.subjectConfig = try container.decodeIfPresent(
      CertificateConfig.SubjectConfig.self, forKey: .subjectConfig)
    self.x509Config = try container.decodeIfPresent(X509Parameters.self, forKey: .x509Config)
    self.publicKey = try container.decodeIfPresent(PublicKey.self, forKey: .publicKey)
    self.subjectKeyId = try container.decodeIfPresent(
      CertificateConfig.KeyId.self, forKey: .subjectKeyId)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.subjectConfig, forKey: .subjectConfig)
    try container.encodeIfPresent(self.x509Config, forKey: .x509Config)
    try container.encodeIfPresent(self.publicKey, forKey: .publicKey)
    try container.encodeIfPresent(self.subjectKeyId, forKey: .subjectKeyId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// These values are used to create the distinguished name and subject
  /// alternative name fields in an X.509 certificate.
  public struct SubjectConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. Contains distinguished name fields such as the common name,
    /// location and organization.
    public var subject: Subject? = nil

    /// Optional. The subject alternative name fields.
    public var subjectAltName: SubjectAltNames? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `SubjectConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SubjectConfig().with { $0.subject = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let subject = CodingKeys(stringValue: "subject")
      static let subjectAltName = CodingKeys(stringValue: "subjectAltName")

      static let _knownKeys: Set<Swift.String> = [
        "subject",
        "subjectAltName",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.subject = try container.decodeIfPresent(Subject.self, forKey: .subject)
      self.subjectAltName = try container.decodeIfPresent(
        SubjectAltNames.self, forKey: .subjectAltName)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.subject, forKey: .subject)
      try container.encodeIfPresent(self.subjectAltName, forKey: .subjectAltName)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.security.privateca.v1.CertificateConfig.SubjectConfig"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// A KeyId identifies a specific public key, usually by hashing the public
  /// key.
  public struct KeyId: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. The value of this KeyId encoded in lowercase hexadecimal. This
    /// is most likely the 160 bit SHA-1 hash of the public key.
    public var keyId: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `KeyId`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = KeyId().with { $0.keyId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let keyId = CodingKeys(stringValue: "keyId")

      static let _knownKeys: Set<Swift.String> = [
        "keyId"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .keyId) {
        self.keyId = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.keyId, forKey: .keyId)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.security.privateca.v1.CertificateConfig.KeyId"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.security.privateca.v1.CertificateConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
