// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol CertificateAuthorityServiceStub: Sendable {
    func createCertificate(
      request: CreateCertificateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityPrivateCAV1.Certificate

    func getCertificate(
      request: GetCertificateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityPrivateCAV1.Certificate

    func listCertificates(
      request: ListCertificatesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityPrivateCAV1.ListCertificatesResponse

    func revokeCertificate(
      request: RevokeCertificateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityPrivateCAV1.Certificate

    func updateCertificate(
      request: UpdateCertificateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityPrivateCAV1.Certificate

    func activateCertificateAuthority(
      request: ActivateCertificateAuthorityRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createCertificateAuthority(
      request: CreateCertificateAuthorityRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func disableCertificateAuthority(
      request: DisableCertificateAuthorityRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func enableCertificateAuthority(
      request: EnableCertificateAuthorityRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func fetchCertificateAuthorityCsr(
      request: FetchCertificateAuthorityCsrRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityPrivateCAV1.FetchCertificateAuthorityCsrResponse

    func getCertificateAuthority(
      request: GetCertificateAuthorityRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityPrivateCAV1.CertificateAuthority

    func listCertificateAuthorities(
      request: ListCertificateAuthoritiesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityPrivateCAV1.ListCertificateAuthoritiesResponse

    func undeleteCertificateAuthority(
      request: UndeleteCertificateAuthorityRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteCertificateAuthority(
      request: DeleteCertificateAuthorityRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateCertificateAuthority(
      request: UpdateCertificateAuthorityRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createCaPool(
      request: CreateCaPoolRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateCaPool(
      request: UpdateCaPoolRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getCaPool(
      request: GetCaPoolRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityPrivateCAV1.CaPool

    func listCaPools(
      request: ListCaPoolsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityPrivateCAV1.ListCaPoolsResponse

    func deleteCaPool(
      request: DeleteCaPoolRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func fetchCaCerts(
      request: FetchCaCertsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityPrivateCAV1.FetchCaCertsResponse

    func getCertificateRevocationList(
      request: GetCertificateRevocationListRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityPrivateCAV1.CertificateRevocationList

    func listCertificateRevocationLists(
      request: ListCertificateRevocationListsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityPrivateCAV1.ListCertificateRevocationListsResponse

    func updateCertificateRevocationList(
      request: UpdateCertificateRevocationListRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createCertificateTemplate(
      request: CreateCertificateTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteCertificateTemplate(
      request: DeleteCertificateTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getCertificateTemplate(
      request: GetCertificateTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityPrivateCAV1.CertificateTemplate

    func listCertificateTemplates(
      request: ListCertificateTemplatesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityPrivateCAV1.ListCertificateTemplatesResponse

    func updateCertificateTemplate(
      request: UpdateCertificateTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}
