// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleType
@_spi(GoogleCloudInternal) import GoogleWKT

/// Describes constraints on a
/// [Certificate][google.cloud.security.privateca.v1.Certificate]'s
/// [Subject][google.cloud.security.privateca.v1.Subject] and
/// [SubjectAltNames][google.cloud.security.privateca.v1.SubjectAltNames].
///
/// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
/// [google.cloud.security.privateca.v1.Subject]: <doc:Subject>
/// [google.cloud.security.privateca.v1.SubjectAltNames]: <doc:SubjectAltNames>
public struct CertificateIdentityConstraints: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. A CEL expression that may be used to validate the resolved X.509
  /// Subject and/or Subject Alternative Name before a certificate is signed. To
  /// see the full allowed syntax and some examples, see
  /// https://cloud.google.com/certificate-authority-service/docs/using-cel
  public var celExpression: GoogleType.Expr? = nil

  /// Required. If this is true, the
  /// [Subject][google.cloud.security.privateca.v1.Subject] field may be copied
  /// from a certificate request into the signed certificate. Otherwise, the
  /// requested [Subject][google.cloud.security.privateca.v1.Subject] will be
  /// discarded.
  ///
  /// [google.cloud.security.privateca.v1.Subject]: <doc:Subject>
  public var allowSubjectPassthrough: Swift.Bool? = nil

  /// Required. If this is true, the
  /// [SubjectAltNames][google.cloud.security.privateca.v1.SubjectAltNames]
  /// extension may be copied from a certificate request into the signed
  /// certificate. Otherwise, the requested
  /// [SubjectAltNames][google.cloud.security.privateca.v1.SubjectAltNames] will
  /// be discarded.
  ///
  /// [google.cloud.security.privateca.v1.SubjectAltNames]: <doc:SubjectAltNames>
  public var allowSubjectAltNamesPassthrough: Swift.Bool? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CertificateIdentityConstraints`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CertificateIdentityConstraints().with { $0.celExpression = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let celExpression = CodingKeys(stringValue: "celExpression")
    static let allowSubjectPassthrough = CodingKeys(stringValue: "allowSubjectPassthrough")
    static let allowSubjectAltNamesPassthrough = CodingKeys(
      stringValue: "allowSubjectAltNamesPassthrough")

    static let _knownKeys: Set<Swift.String> = [
      "celExpression",
      "allowSubjectPassthrough",
      "allowSubjectAltNamesPassthrough",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.celExpression = try container.decodeIfPresent(GoogleType.Expr.self, forKey: .celExpression)
    self.allowSubjectPassthrough = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .allowSubjectPassthrough)
    self.allowSubjectAltNamesPassthrough = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .allowSubjectAltNamesPassthrough)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.celExpression, forKey: .celExpression)
    try container.encodeIfPresent(self.allowSubjectPassthrough, forKey: .allowSubjectPassthrough)
    try container.encodeIfPresent(
      self.allowSubjectAltNamesPassthrough, forKey: .allowSubjectAltNamesPassthrough)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.security.privateca.v1.CertificateIdentityConstraints"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
