// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A
/// [CertificateTemplate][google.cloud.security.privateca.v1.CertificateTemplate]
/// refers to a managed template for certificate issuance.
///
/// [google.cloud.security.privateca.v1.CertificateTemplate]: <doc:CertificateTemplate>
public struct CertificateTemplate: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name for this
  /// [CertificateTemplate][google.cloud.security.privateca.v1.CertificateTemplate]
  /// in the format `projects/*/locations/*/certificateTemplates/*`.
  ///
  /// [google.cloud.security.privateca.v1.CertificateTemplate]: <doc:CertificateTemplate>
  public var name: Swift.String = Swift.String()

  /// Optional. The maximum lifetime allowed for issued
  /// [Certificates][google.cloud.security.privateca.v1.Certificate] that use
  /// this template. If the issuing
  /// [CaPool][google.cloud.security.privateca.v1.CaPool] resource's
  /// [IssuancePolicy][google.cloud.security.privateca.v1.CaPool.IssuancePolicy]
  /// specifies a
  /// [maximum_lifetime][google.cloud.security.privateca.v1.CaPool.IssuancePolicy.maximum_lifetime]
  /// the minimum of the two durations will be the maximum lifetime for issued
  /// [Certificates][google.cloud.security.privateca.v1.Certificate]. Note that
  /// if the issuing
  /// [CertificateAuthority][google.cloud.security.privateca.v1.CertificateAuthority]
  /// expires before a
  /// [Certificate][google.cloud.security.privateca.v1.Certificate]'s requested
  /// maximum_lifetime, the effective lifetime will be explicitly truncated
  ///  to match it.
  ///
  /// [google.cloud.security.privateca.v1.CaPool]: <doc:CaPool>
  /// [google.cloud.security.privateca.v1.CaPool.IssuancePolicy]: <doc:CaPool/IssuancePolicy>
  /// [google.cloud.security.privateca.v1.CaPool.IssuancePolicy.maximum_lifetime]: <doc:CaPool/IssuancePolicy/maximumLifetime>
  /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
  /// [google.cloud.security.privateca.v1.CertificateAuthority]: <doc:CertificateAuthority>
  public var maximumLifetime: GoogleWKT.WKTDuration? = nil

  /// Optional. A set of X.509 values that will be applied to all issued
  /// certificates that use this template. If the certificate request includes
  /// conflicting values for the same properties, they will be overwritten by the
  /// values defined here. If the issuing
  /// [CaPool][google.cloud.security.privateca.v1.CaPool]'s
  /// [IssuancePolicy][google.cloud.security.privateca.v1.CaPool.IssuancePolicy]
  /// defines conflicting
  /// [baseline_values][google.cloud.security.privateca.v1.CaPool.IssuancePolicy.baseline_values]
  /// for the same properties, the certificate issuance request will fail.
  ///
  /// [google.cloud.security.privateca.v1.CaPool]: <doc:CaPool>
  /// [google.cloud.security.privateca.v1.CaPool.IssuancePolicy]: <doc:CaPool/IssuancePolicy>
  /// [google.cloud.security.privateca.v1.CaPool.IssuancePolicy.baseline_values]: <doc:CaPool/IssuancePolicy/baselineValues>
  public var predefinedValues: X509Parameters? = nil

  /// Optional. Describes constraints on identities that may be appear in
  /// [Certificates][google.cloud.security.privateca.v1.Certificate] issued using
  /// this template. If this is omitted, then this template will not add
  /// restrictions on a certificate's identity.
  ///
  /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
  public var identityConstraints: CertificateIdentityConstraints? = nil

  /// Optional. Describes the set of X.509 extensions that may appear in a
  /// [Certificate][google.cloud.security.privateca.v1.Certificate] issued using
  /// this
  /// [CertificateTemplate][google.cloud.security.privateca.v1.CertificateTemplate].
  /// If a certificate request sets extensions that don't appear in the
  /// [passthrough_extensions][google.cloud.security.privateca.v1.CertificateTemplate.passthrough_extensions],
  /// those extensions will be dropped. If the issuing
  /// [CaPool][google.cloud.security.privateca.v1.CaPool]'s
  /// [IssuancePolicy][google.cloud.security.privateca.v1.CaPool.IssuancePolicy]
  /// defines
  /// [baseline_values][google.cloud.security.privateca.v1.CaPool.IssuancePolicy.baseline_values]
  /// that don't appear here, the certificate issuance request will fail. If this
  /// is omitted, then this template will not add restrictions on a certificate's
  /// X.509 extensions. These constraints do not apply to X.509 extensions set in
  /// this
  /// [CertificateTemplate][google.cloud.security.privateca.v1.CertificateTemplate]'s
  /// [predefined_values][google.cloud.security.privateca.v1.CertificateTemplate.predefined_values].
  ///
  /// [google.cloud.security.privateca.v1.CaPool]: <doc:CaPool>
  /// [google.cloud.security.privateca.v1.CaPool.IssuancePolicy]: <doc:CaPool/IssuancePolicy>
  /// [google.cloud.security.privateca.v1.CaPool.IssuancePolicy.baseline_values]: <doc:CaPool/IssuancePolicy/baselineValues>
  /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
  /// [google.cloud.security.privateca.v1.CertificateTemplate]: <doc:CertificateTemplate>
  /// [google.cloud.security.privateca.v1.CertificateTemplate.passthrough_extensions]: <doc:CertificateTemplate/passthroughExtensions>
  /// [google.cloud.security.privateca.v1.CertificateTemplate.predefined_values]: <doc:CertificateTemplate/predefinedValues>
  public var passthroughExtensions: CertificateExtensionConstraints? = nil

  /// Optional. A human-readable description of scenarios this template is
  /// intended for.
  public var description: Swift.String = Swift.String()

  /// Output only. The time at which this
  /// [CertificateTemplate][google.cloud.security.privateca.v1.CertificateTemplate]
  /// was created.
  ///
  /// [google.cloud.security.privateca.v1.CertificateTemplate]: <doc:CertificateTemplate>
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time at which this
  /// [CertificateTemplate][google.cloud.security.privateca.v1.CertificateTemplate]
  /// was updated.
  ///
  /// [google.cloud.security.privateca.v1.CertificateTemplate]: <doc:CertificateTemplate>
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. Labels with user-defined metadata.
  public var labels: [Swift.String: Swift.String] = [:]

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CertificateTemplate`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CertificateTemplate().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let maximumLifetime = CodingKeys(stringValue: "maximumLifetime")
    static let predefinedValues = CodingKeys(stringValue: "predefinedValues")
    static let identityConstraints = CodingKeys(stringValue: "identityConstraints")
    static let passthroughExtensions = CodingKeys(stringValue: "passthroughExtensions")
    static let description = CodingKeys(stringValue: "description")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "maximumLifetime",
      "predefinedValues",
      "identityConstraints",
      "passthroughExtensions",
      "description",
      "createTime",
      "updateTime",
      "labels",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.maximumLifetime = try container.decodeIfPresent(
      GoogleWKT.WKTDuration.self, forKey: .maximumLifetime)
    self.predefinedValues = try container.decodeIfPresent(
      X509Parameters.self, forKey: .predefinedValues)
    self.identityConstraints = try container.decodeIfPresent(
      CertificateIdentityConstraints.self, forKey: .identityConstraints)
    self.passthroughExtensions = try container.decodeIfPresent(
      CertificateExtensionConstraints.self, forKey: .passthroughExtensions)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.maximumLifetime, forKey: .maximumLifetime)
    try container.encodeIfPresent(self.predefinedValues, forKey: .predefinedValues)
    try container.encodeIfPresent(self.identityConstraints, forKey: .identityConstraints)
    try container.encodeIfPresent(self.passthroughExtensions, forKey: .passthroughExtensions)
    try container.encode(self.description, forKey: .description)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.security.privateca.v1.CertificateTemplate"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
