// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A
/// [CertificateRevocationList][google.cloud.security.privateca.v1.CertificateRevocationList]
/// corresponds to a signed X.509 certificate Revocation List (CRL). A CRL
/// contains the serial numbers of certificates that should no longer be trusted.
///
/// [google.cloud.security.privateca.v1.CertificateRevocationList]: <doc:CertificateRevocationList>
public struct CertificateRevocationList: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name for this
  /// [CertificateRevocationList][google.cloud.security.privateca.v1.CertificateRevocationList]
  /// in the format `projects/*/locations/*/caPools/*certificateAuthorities/*/
  ///    certificateRevocationLists/*`.
  ///
  /// [google.cloud.security.privateca.v1.CertificateRevocationList]: <doc:CertificateRevocationList>
  public var name: Swift.String = Swift.String()

  /// Output only. The CRL sequence number that appears in pem_crl.
  public var sequenceNumber: Swift.Int64 = Swift.Int64()

  /// Output only. The revoked serial numbers that appear in pem_crl.
  public var revokedCertificates: [CertificateRevocationList.RevokedCertificate] = []

  /// Output only. The PEM-encoded X.509 CRL.
  public var pemCrl: Swift.String = Swift.String()

  /// Output only. The location where 'pem_crl' can be accessed.
  public var accessUrl: Swift.String = Swift.String()

  /// Output only. The
  /// [State][google.cloud.security.privateca.v1.CertificateRevocationList.State]
  /// for this
  /// [CertificateRevocationList][google.cloud.security.privateca.v1.CertificateRevocationList].
  ///
  /// [google.cloud.security.privateca.v1.CertificateRevocationList]: <doc:CertificateRevocationList>
  /// [google.cloud.security.privateca.v1.CertificateRevocationList.State]: <doc:CertificateRevocationList/State>
  public var state: CertificateRevocationList.State = CertificateRevocationList.State()

  /// Output only. The time at which this
  /// [CertificateRevocationList][google.cloud.security.privateca.v1.CertificateRevocationList]
  /// was created.
  ///
  /// [google.cloud.security.privateca.v1.CertificateRevocationList]: <doc:CertificateRevocationList>
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The time at which this
  /// [CertificateRevocationList][google.cloud.security.privateca.v1.CertificateRevocationList]
  /// was updated.
  ///
  /// [google.cloud.security.privateca.v1.CertificateRevocationList]: <doc:CertificateRevocationList>
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The revision ID of this
  /// [CertificateRevocationList][google.cloud.security.privateca.v1.CertificateRevocationList].
  /// A new revision is committed whenever a new CRL is published. The format is
  /// an 8-character hexadecimal string.
  ///
  /// [google.cloud.security.privateca.v1.CertificateRevocationList]: <doc:CertificateRevocationList>
  public var revisionId: Swift.String = Swift.String()

  /// Optional. Labels with user-defined metadata.
  public var labels: [Swift.String: Swift.String] = [:]

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `CertificateRevocationList`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CertificateRevocationList().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let sequenceNumber = CodingKeys(stringValue: "sequenceNumber")
    static let revokedCertificates = CodingKeys(stringValue: "revokedCertificates")
    static let pemCrl = CodingKeys(stringValue: "pemCrl")
    static let accessUrl = CodingKeys(stringValue: "accessUrl")
    static let state = CodingKeys(stringValue: "state")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let revisionId = CodingKeys(stringValue: "revisionId")
    static let labels = CodingKeys(stringValue: "labels")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "sequenceNumber",
      "revokedCertificates",
      "pemCrl",
      "accessUrl",
      "state",
      "createTime",
      "updateTime",
      "revisionId",
      "labels",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .sequenceNumber) {
      self.sequenceNumber = value
    }
    if let value = try container.decodeIfPresent(
      [CertificateRevocationList.RevokedCertificate].self, forKey: .revokedCertificates)
    {
      self.revokedCertificates = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pemCrl) {
      self.pemCrl = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .accessUrl) {
      self.accessUrl = value
    }
    if let value = try container.decodeIfPresent(
      CertificateRevocationList.State.self, forKey: .state)
    {
      self.state = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .revisionId) {
      self.revisionId = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.sequenceNumber, forKey: .sequenceNumber)
    try container.encode(self.revokedCertificates, forKey: .revokedCertificates)
    try container.encode(self.pemCrl, forKey: .pemCrl)
    try container.encode(self.accessUrl, forKey: .accessUrl)
    try container.encode(self.state, forKey: .state)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.revisionId, forKey: .revisionId)
    try container.encode(self.labels, forKey: .labels)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Describes a revoked
  /// [Certificate][google.cloud.security.privateca.v1.Certificate].
  ///
  /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
  public struct RevokedCertificate: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The resource name for the
    /// [Certificate][google.cloud.security.privateca.v1.Certificate] in the
    /// format `projects/*/locations/*/caPools/*/certificates/*`.
    ///
    /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
    public var certificate: Swift.String = Swift.String()

    /// The serial number of the
    /// [Certificate][google.cloud.security.privateca.v1.Certificate].
    ///
    /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
    public var hexSerialNumber: Swift.String = Swift.String()

    /// The reason the
    /// [Certificate][google.cloud.security.privateca.v1.Certificate] was
    /// revoked.
    ///
    /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
    public var revocationReason: RevocationReason = RevocationReason()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `RevokedCertificate`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RevokedCertificate().with { $0.certificate = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let certificate = CodingKeys(stringValue: "certificate")
      static let hexSerialNumber = CodingKeys(stringValue: "hexSerialNumber")
      static let revocationReason = CodingKeys(stringValue: "revocationReason")

      static let _knownKeys: Set<Swift.String> = [
        "certificate",
        "hexSerialNumber",
        "revocationReason",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .certificate) {
        self.certificate = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .hexSerialNumber) {
        self.hexSerialNumber = value
      }
      if let value = try container.decodeIfPresent(RevocationReason.self, forKey: .revocationReason)
      {
        self.revocationReason = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.certificate, forKey: .certificate)
      try container.encode(self.hexSerialNumber, forKey: .hexSerialNumber)
      try container.encode(self.revocationReason, forKey: .revocationReason)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.security.privateca.v1.CertificateRevocationList.RevokedCertificate"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// The state of a
  /// [CertificateRevocationList][google.cloud.security.privateca.v1.CertificateRevocationList],
  /// indicating if it is current.
  ///
  /// [google.cloud.security.privateca.v1.CertificateRevocationList]: <doc:CertificateRevocationList>
  public enum State: Codable, Equatable, Sendable {
    /// Not specified.
    case unspecified
    /// The
    /// [CertificateRevocationList][google.cloud.security.privateca.v1.CertificateRevocationList]
    /// is up to date.
    ///
    /// [google.cloud.security.privateca.v1.CertificateRevocationList]: <doc:CertificateRevocationList>
    case active
    /// The
    /// [CertificateRevocationList][google.cloud.security.privateca.v1.CertificateRevocationList]
    /// is no longer current.
    ///
    /// [google.cloud.security.privateca.v1.CertificateRevocationList]: <doc:CertificateRevocationList>
    case superseded
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 1
      case .superseded: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .active: return "ACTIVE"
      case .superseded: return "SUPERSEDED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ACTIVE": self = .active
      case "SUPERSEDED": self = .superseded
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .active
      case 2: self = .superseded
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .active: return try container.encode("ACTIVE")
      case .superseded: return try container.encode("SUPERSEDED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.security.privateca.v1.CertificateRevocationList"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
