// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// A
/// [CertificateDescription][google.cloud.security.privateca.v1.CertificateDescription]
/// describes an X.509 certificate or CSR that has been issued, as an alternative
/// to using ASN.1 / X.509.
///
/// [google.cloud.security.privateca.v1.CertificateDescription]: <doc:CertificateDescription>
public struct CertificateDescription: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Describes some of the values in a certificate that are related to the
  /// subject and lifetime.
  public var subjectDescription: CertificateDescription.SubjectDescription? = nil

  /// Describes some of the technical X.509 fields in a certificate.
  public var x509Description: X509Parameters? = nil

  /// The public key that corresponds to an issued certificate.
  public var publicKey: PublicKey? = nil

  /// Provides a means of identifiying certificates that contain a particular
  /// public key, per https://tools.ietf.org/html/rfc5280#section-4.2.1.2.
  public var subjectKeyId: CertificateDescription.KeyId? = nil

  /// Identifies the subject_key_id of the parent certificate, per
  /// https://tools.ietf.org/html/rfc5280#section-4.2.1.1
  public var authorityKeyId: CertificateDescription.KeyId? = nil

  /// Describes a list of locations to obtain CRL information, i.e.
  /// the DistributionPoint.fullName described by
  /// https://tools.ietf.org/html/rfc5280#section-4.2.1.13
  public var crlDistributionPoints: [Swift.String] = []

  /// Describes lists of issuer CA certificate URLs that appear in the
  /// "Authority Information Access" extension in the certificate.
  public var aiaIssuingCertificateUrls: [Swift.String] = []

  /// The hash of the x.509 certificate.
  public var certFingerprint: CertificateDescription.CertificateFingerprint? = nil

  /// The hash of the pre-signed certificate, which will be signed by the CA.
  /// Corresponds to the TBS Certificate in
  /// https://tools.ietf.org/html/rfc5280#section-4.1.2. The field will always be
  /// populated.
  public var tbsCertificateDigest: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CertificateDescription`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CertificateDescription().with { $0.subjectDescription = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let subjectDescription = CodingKeys(stringValue: "subjectDescription")
    static let x509Description = CodingKeys(stringValue: "x509Description")
    static let publicKey = CodingKeys(stringValue: "publicKey")
    static let subjectKeyId = CodingKeys(stringValue: "subjectKeyId")
    static let authorityKeyId = CodingKeys(stringValue: "authorityKeyId")
    static let crlDistributionPoints = CodingKeys(stringValue: "crlDistributionPoints")
    static let aiaIssuingCertificateUrls = CodingKeys(stringValue: "aiaIssuingCertificateUrls")
    static let certFingerprint = CodingKeys(stringValue: "certFingerprint")
    static let tbsCertificateDigest = CodingKeys(stringValue: "tbsCertificateDigest")

    static let _knownKeys: Set<Swift.String> = [
      "subjectDescription",
      "x509Description",
      "publicKey",
      "subjectKeyId",
      "authorityKeyId",
      "crlDistributionPoints",
      "aiaIssuingCertificateUrls",
      "certFingerprint",
      "tbsCertificateDigest",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.subjectDescription = try container.decodeIfPresent(
      CertificateDescription.SubjectDescription.self, forKey: .subjectDescription)
    self.x509Description = try container.decodeIfPresent(
      X509Parameters.self, forKey: .x509Description)
    self.publicKey = try container.decodeIfPresent(PublicKey.self, forKey: .publicKey)
    self.subjectKeyId = try container.decodeIfPresent(
      CertificateDescription.KeyId.self, forKey: .subjectKeyId)
    self.authorityKeyId = try container.decodeIfPresent(
      CertificateDescription.KeyId.self, forKey: .authorityKeyId)
    if let value = try container.decodeIfPresent(
      [Swift.String].self, forKey: .crlDistributionPoints)
    {
      self.crlDistributionPoints = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String].self, forKey: .aiaIssuingCertificateUrls)
    {
      self.aiaIssuingCertificateUrls = value
    }
    self.certFingerprint = try container.decodeIfPresent(
      CertificateDescription.CertificateFingerprint.self, forKey: .certFingerprint)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .tbsCertificateDigest) {
      self.tbsCertificateDigest = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.subjectDescription, forKey: .subjectDescription)
    try container.encodeIfPresent(self.x509Description, forKey: .x509Description)
    try container.encodeIfPresent(self.publicKey, forKey: .publicKey)
    try container.encodeIfPresent(self.subjectKeyId, forKey: .subjectKeyId)
    try container.encodeIfPresent(self.authorityKeyId, forKey: .authorityKeyId)
    try container.encode(self.crlDistributionPoints, forKey: .crlDistributionPoints)
    try container.encode(self.aiaIssuingCertificateUrls, forKey: .aiaIssuingCertificateUrls)
    try container.encodeIfPresent(self.certFingerprint, forKey: .certFingerprint)
    try container.encode(self.tbsCertificateDigest, forKey: .tbsCertificateDigest)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// These values describe fields in an issued X.509 certificate such as the
  /// distinguished name, subject alternative names, serial number, and lifetime.
  public struct SubjectDescription: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Contains distinguished name fields such as the common name, location and
    /// / organization.
    public var subject: Subject? = nil

    /// The subject alternative name fields.
    public var subjectAltName: SubjectAltNames? = nil

    /// The serial number encoded in lowercase hexadecimal.
    public var hexSerialNumber: Swift.String = Swift.String()

    /// For convenience, the actual lifetime of an issued certificate.
    public var lifetime: GoogleWKT.Duration? = nil

    /// The time at which the certificate becomes valid.
    public var notBeforeTime: GoogleWKT.Timestamp? = nil

    /// The time after which the certificate is expired.
    /// Per RFC 5280, the validity period for a certificate is the period of time
    /// from not_before_time through not_after_time, inclusive.
    /// Corresponds to 'not_before_time' + 'lifetime' - 1 second.
    public var notAfterTime: GoogleWKT.Timestamp? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SubjectDescription`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SubjectDescription().with { $0.subject = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let subject = CodingKeys(stringValue: "subject")
      static let subjectAltName = CodingKeys(stringValue: "subjectAltName")
      static let hexSerialNumber = CodingKeys(stringValue: "hexSerialNumber")
      static let lifetime = CodingKeys(stringValue: "lifetime")
      static let notBeforeTime = CodingKeys(stringValue: "notBeforeTime")
      static let notAfterTime = CodingKeys(stringValue: "notAfterTime")

      static let _knownKeys: Set<Swift.String> = [
        "subject",
        "subjectAltName",
        "hexSerialNumber",
        "lifetime",
        "notBeforeTime",
        "notAfterTime",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.subject = try container.decodeIfPresent(Subject.self, forKey: .subject)
      self.subjectAltName = try container.decodeIfPresent(
        SubjectAltNames.self, forKey: .subjectAltName)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .hexSerialNumber) {
        self.hexSerialNumber = value
      }
      self.lifetime = try container.decodeIfPresent(GoogleWKT.Duration.self, forKey: .lifetime)
      self.notBeforeTime = try container.decodeIfPresent(
        GoogleWKT.Timestamp.self, forKey: .notBeforeTime)
      self.notAfterTime = try container.decodeIfPresent(
        GoogleWKT.Timestamp.self, forKey: .notAfterTime)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.subject, forKey: .subject)
      try container.encodeIfPresent(self.subjectAltName, forKey: .subjectAltName)
      try container.encode(self.hexSerialNumber, forKey: .hexSerialNumber)
      try container.encodeIfPresent(self.lifetime, forKey: .lifetime)
      try container.encodeIfPresent(self.notBeforeTime, forKey: .notBeforeTime)
      try container.encodeIfPresent(self.notAfterTime, forKey: .notAfterTime)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.security.privateca.v1.CertificateDescription.SubjectDescription"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// A KeyId identifies a specific public key, usually by hashing the public
  /// key.
  public struct KeyId: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. The value of this KeyId encoded in lowercase hexadecimal. This
    /// is most likely the 160 bit SHA-1 hash of the public key.
    public var keyId: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `KeyId`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = KeyId().with { $0.keyId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let keyId = CodingKeys(stringValue: "keyId")

      static let _knownKeys: Set<Swift.String> = [
        "keyId"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .keyId) {
        self.keyId = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.keyId, forKey: .keyId)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.security.privateca.v1.CertificateDescription.KeyId"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// A group of fingerprints for the x509 certificate.
  public struct CertificateFingerprint: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The SHA 256 hash, encoded in hexadecimal, of the DER x509 certificate.
    public var sha256Hash: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `CertificateFingerprint`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CertificateFingerprint().with { $0.sha256Hash = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let sha256Hash = CodingKeys(stringValue: "sha256Hash")

      static let _knownKeys: Set<Swift.String> = [
        "sha256Hash"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sha256Hash) {
        self.sha256Hash = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.sha256Hash, forKey: .sha256Hash)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.security.privateca.v1.CertificateDescription.CertificateFingerprint"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.security.privateca.v1.CertificateDescription"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
