// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class CertificateAuthorityServiceLogging: CertificateAuthorityServiceStub {
    let inner: any CertificateAuthorityServiceStub
    let logger: Logger

    public init(_ inner: any CertificateAuthorityServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-security-privateca-v1"
      logger[metadataKey: "gcp.client.service"] = "privateca"
      logger[metadataKey: "gcp.experimental.swift.client"] = "CertificateAuthorityService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func createCertificate(
      request: CreateCertificateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityPrivateCAV1.Certificate {
      try await self._intercept(
        request: request,
        options: options,
        name: "createCertificate",
        action: {
          (r: CreateCertificateRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecurityPrivateCAV1.Certificate
          in
          return try await self.inner.createCertificate(request: r, options: o)
        })
    }

    public func getCertificate(
      request: GetCertificateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityPrivateCAV1.Certificate {
      try await self._intercept(
        request: request,
        options: options,
        name: "getCertificate",
        action: {
          (r: GetCertificateRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecurityPrivateCAV1.Certificate
          in
          return try await self.inner.getCertificate(request: r, options: o)
        })
    }

    public func listCertificates(
      request: ListCertificatesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityPrivateCAV1.ListCertificatesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listCertificates",
        action: {
          (r: ListCertificatesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecurityPrivateCAV1.ListCertificatesResponse
          in
          return try await self.inner.listCertificates(request: r, options: o)
        })
    }

    public func revokeCertificate(
      request: RevokeCertificateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityPrivateCAV1.Certificate {
      try await self._intercept(
        request: request,
        options: options,
        name: "revokeCertificate",
        action: {
          (r: RevokeCertificateRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecurityPrivateCAV1.Certificate
          in
          return try await self.inner.revokeCertificate(request: r, options: o)
        })
    }

    public func updateCertificate(
      request: UpdateCertificateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityPrivateCAV1.Certificate {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateCertificate",
        action: {
          (r: UpdateCertificateRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecurityPrivateCAV1.Certificate
          in
          return try await self.inner.updateCertificate(request: r, options: o)
        })
    }

    public func activateCertificateAuthority(
      request: ActivateCertificateAuthorityRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "activateCertificateAuthority",
        action: {
          (r: ActivateCertificateAuthorityRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.activateCertificateAuthority(request: r, options: o)
        })
    }

    public func createCertificateAuthority(
      request: CreateCertificateAuthorityRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createCertificateAuthority",
        action: {
          (r: CreateCertificateAuthorityRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createCertificateAuthority(request: r, options: o)
        })
    }

    public func disableCertificateAuthority(
      request: DisableCertificateAuthorityRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "disableCertificateAuthority",
        action: {
          (r: DisableCertificateAuthorityRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.disableCertificateAuthority(request: r, options: o)
        })
    }

    public func enableCertificateAuthority(
      request: EnableCertificateAuthorityRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "enableCertificateAuthority",
        action: {
          (r: EnableCertificateAuthorityRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.enableCertificateAuthority(request: r, options: o)
        })
    }

    public func fetchCertificateAuthorityCsr(
      request: FetchCertificateAuthorityCsrRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityPrivateCAV1.FetchCertificateAuthorityCsrResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "fetchCertificateAuthorityCsr",
        action: {
          (r: FetchCertificateAuthorityCsrRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecurityPrivateCAV1.FetchCertificateAuthorityCsrResponse
          in
          return try await self.inner.fetchCertificateAuthorityCsr(request: r, options: o)
        })
    }

    public func getCertificateAuthority(
      request: GetCertificateAuthorityRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityPrivateCAV1.CertificateAuthority {
      try await self._intercept(
        request: request,
        options: options,
        name: "getCertificateAuthority",
        action: {
          (r: GetCertificateAuthorityRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecurityPrivateCAV1.CertificateAuthority
          in
          return try await self.inner.getCertificateAuthority(request: r, options: o)
        })
    }

    public func listCertificateAuthorities(
      request: ListCertificateAuthoritiesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityPrivateCAV1.ListCertificateAuthoritiesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listCertificateAuthorities",
        action: {
          (r: ListCertificateAuthoritiesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecurityPrivateCAV1.ListCertificateAuthoritiesResponse
          in
          return try await self.inner.listCertificateAuthorities(request: r, options: o)
        })
    }

    public func undeleteCertificateAuthority(
      request: UndeleteCertificateAuthorityRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "undeleteCertificateAuthority",
        action: {
          (r: UndeleteCertificateAuthorityRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.undeleteCertificateAuthority(request: r, options: o)
        })
    }

    public func deleteCertificateAuthority(
      request: DeleteCertificateAuthorityRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteCertificateAuthority",
        action: {
          (r: DeleteCertificateAuthorityRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteCertificateAuthority(request: r, options: o)
        })
    }

    public func updateCertificateAuthority(
      request: UpdateCertificateAuthorityRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateCertificateAuthority",
        action: {
          (r: UpdateCertificateAuthorityRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateCertificateAuthority(request: r, options: o)
        })
    }

    public func createCaPool(
      request: CreateCaPoolRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createCaPool",
        action: {
          (r: CreateCaPoolRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createCaPool(request: r, options: o)
        })
    }

    public func updateCaPool(
      request: UpdateCaPoolRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateCaPool",
        action: {
          (r: UpdateCaPoolRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateCaPool(request: r, options: o)
        })
    }

    public func getCaPool(
      request: GetCaPoolRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityPrivateCAV1.CaPool {
      try await self._intercept(
        request: request,
        options: options,
        name: "getCaPool",
        action: {
          (r: GetCaPoolRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecurityPrivateCAV1.CaPool
          in
          return try await self.inner.getCaPool(request: r, options: o)
        })
    }

    public func listCaPools(
      request: ListCaPoolsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityPrivateCAV1.ListCaPoolsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listCaPools",
        action: {
          (r: ListCaPoolsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecurityPrivateCAV1.ListCaPoolsResponse
          in
          return try await self.inner.listCaPools(request: r, options: o)
        })
    }

    public func deleteCaPool(
      request: DeleteCaPoolRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteCaPool",
        action: {
          (r: DeleteCaPoolRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteCaPool(request: r, options: o)
        })
    }

    public func fetchCaCerts(
      request: FetchCaCertsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityPrivateCAV1.FetchCaCertsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "fetchCaCerts",
        action: {
          (r: FetchCaCertsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecurityPrivateCAV1.FetchCaCertsResponse
          in
          return try await self.inner.fetchCaCerts(request: r, options: o)
        })
    }

    public func getCertificateRevocationList(
      request: GetCertificateRevocationListRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityPrivateCAV1.CertificateRevocationList {
      try await self._intercept(
        request: request,
        options: options,
        name: "getCertificateRevocationList",
        action: {
          (r: GetCertificateRevocationListRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecurityPrivateCAV1.CertificateRevocationList
          in
          return try await self.inner.getCertificateRevocationList(request: r, options: o)
        })
    }

    public func listCertificateRevocationLists(
      request: ListCertificateRevocationListsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityPrivateCAV1.ListCertificateRevocationListsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listCertificateRevocationLists",
        action: {
          (r: ListCertificateRevocationListsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecurityPrivateCAV1.ListCertificateRevocationListsResponse
          in
          return try await self.inner.listCertificateRevocationLists(request: r, options: o)
        })
    }

    public func updateCertificateRevocationList(
      request: UpdateCertificateRevocationListRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateCertificateRevocationList",
        action: {
          (r: UpdateCertificateRevocationListRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateCertificateRevocationList(request: r, options: o)
        })
    }

    public func createCertificateTemplate(
      request: CreateCertificateTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createCertificateTemplate",
        action: {
          (r: CreateCertificateTemplateRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createCertificateTemplate(request: r, options: o)
        })
    }

    public func deleteCertificateTemplate(
      request: DeleteCertificateTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteCertificateTemplate",
        action: {
          (r: DeleteCertificateTemplateRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteCertificateTemplate(request: r, options: o)
        })
    }

    public func getCertificateTemplate(
      request: GetCertificateTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityPrivateCAV1.CertificateTemplate {
      try await self._intercept(
        request: request,
        options: options,
        name: "getCertificateTemplate",
        action: {
          (r: GetCertificateTemplateRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecurityPrivateCAV1.CertificateTemplate
          in
          return try await self.inner.getCertificateTemplate(request: r, options: o)
        })
    }

    public func listCertificateTemplates(
      request: ListCertificateTemplatesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecurityPrivateCAV1.ListCertificateTemplatesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listCertificateTemplates",
        action: {
          (r: ListCertificateTemplatesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecurityPrivateCAV1.ListCertificateTemplatesResponse
          in
          return try await self.inner.listCertificateTemplates(request: r, options: o)
        })
    }

    public func updateCertificateTemplate(
      request: UpdateCertificateTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateCertificateTemplate",
        action: {
          (r: UpdateCertificateTemplateRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateCertificateTemplate(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "setIamPolicy",
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIamPolicy",
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "testIamPermissions",
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
