// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A [KeyUsage][google.cloud.security.privateca.v1.KeyUsage] describes key usage
/// values that may appear in an X.509 certificate.
///
/// [google.cloud.security.privateca.v1.KeyUsage]: <doc:KeyUsage>
public struct KeyUsage: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Describes high-level ways in which a key may be used.
  public var baseKeyUsage: KeyUsage.KeyUsageOptions? = nil

  /// Detailed scenarios in which a key may be used.
  public var extendedKeyUsage: KeyUsage.ExtendedKeyUsageOptions? = nil

  /// Used to describe extended key usages that are not listed in the
  /// [KeyUsage.ExtendedKeyUsageOptions][google.cloud.security.privateca.v1.KeyUsage.ExtendedKeyUsageOptions]
  /// message.
  ///
  /// [google.cloud.security.privateca.v1.KeyUsage.ExtendedKeyUsageOptions]: <doc:KeyUsage/ExtendedKeyUsageOptions>
  public var unknownExtendedKeyUsages: [ObjectId] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `KeyUsage`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = KeyUsage().with { $0.baseKeyUsage = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let baseKeyUsage = CodingKeys(stringValue: "baseKeyUsage")
    static let extendedKeyUsage = CodingKeys(stringValue: "extendedKeyUsage")
    static let unknownExtendedKeyUsages = CodingKeys(stringValue: "unknownExtendedKeyUsages")

    static let _knownKeys: Set<Swift.String> = [
      "baseKeyUsage",
      "extendedKeyUsage",
      "unknownExtendedKeyUsages",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.baseKeyUsage = try container.decodeIfPresent(
      KeyUsage.KeyUsageOptions.self, forKey: .baseKeyUsage)
    self.extendedKeyUsage = try container.decodeIfPresent(
      KeyUsage.ExtendedKeyUsageOptions.self, forKey: .extendedKeyUsage)
    if let value = try container.decodeIfPresent([ObjectId].self, forKey: .unknownExtendedKeyUsages)
    {
      self.unknownExtendedKeyUsages = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.baseKeyUsage, forKey: .baseKeyUsage)
    try container.encodeIfPresent(self.extendedKeyUsage, forKey: .extendedKeyUsage)
    try container.encode(self.unknownExtendedKeyUsages, forKey: .unknownExtendedKeyUsages)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// [KeyUsage.KeyUsageOptions][google.cloud.security.privateca.v1.KeyUsage.KeyUsageOptions]
  /// corresponds to the key usage values described in
  /// https://tools.ietf.org/html/rfc5280#section-4.2.1.3.
  ///
  /// [google.cloud.security.privateca.v1.KeyUsage.KeyUsageOptions]: <doc:KeyUsage/KeyUsageOptions>
  public struct KeyUsageOptions: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The key may be used for digital signatures.
    public var digitalSignature: Swift.Bool = Swift.Bool()

    /// The key may be used for cryptographic commitments. Note that this may
    /// also be referred to as "non-repudiation".
    public var contentCommitment: Swift.Bool = Swift.Bool()

    /// The key may be used to encipher other keys.
    public var keyEncipherment: Swift.Bool = Swift.Bool()

    /// The key may be used to encipher data.
    public var dataEncipherment: Swift.Bool = Swift.Bool()

    /// The key may be used in a key agreement protocol.
    public var keyAgreement: Swift.Bool = Swift.Bool()

    /// The key may be used to sign certificates.
    public var certSign: Swift.Bool = Swift.Bool()

    /// The key may be used sign certificate revocation lists.
    public var crlSign: Swift.Bool = Swift.Bool()

    /// The key may be used to encipher only.
    public var encipherOnly: Swift.Bool = Swift.Bool()

    /// The key may be used to decipher only.
    public var decipherOnly: Swift.Bool = Swift.Bool()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `KeyUsageOptions`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = KeyUsageOptions().with { $0.digitalSignature = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let digitalSignature = CodingKeys(stringValue: "digitalSignature")
      static let contentCommitment = CodingKeys(stringValue: "contentCommitment")
      static let keyEncipherment = CodingKeys(stringValue: "keyEncipherment")
      static let dataEncipherment = CodingKeys(stringValue: "dataEncipherment")
      static let keyAgreement = CodingKeys(stringValue: "keyAgreement")
      static let certSign = CodingKeys(stringValue: "certSign")
      static let crlSign = CodingKeys(stringValue: "crlSign")
      static let encipherOnly = CodingKeys(stringValue: "encipherOnly")
      static let decipherOnly = CodingKeys(stringValue: "decipherOnly")

      static let _knownKeys: Set<Swift.String> = [
        "digitalSignature",
        "contentCommitment",
        "keyEncipherment",
        "dataEncipherment",
        "keyAgreement",
        "certSign",
        "crlSign",
        "encipherOnly",
        "decipherOnly",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .digitalSignature) {
        self.digitalSignature = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .contentCommitment) {
        self.contentCommitment = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .keyEncipherment) {
        self.keyEncipherment = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .dataEncipherment) {
        self.dataEncipherment = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .keyAgreement) {
        self.keyAgreement = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .certSign) {
        self.certSign = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .crlSign) {
        self.crlSign = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .encipherOnly) {
        self.encipherOnly = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .decipherOnly) {
        self.decipherOnly = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.digitalSignature, forKey: .digitalSignature)
      try container.encode(self.contentCommitment, forKey: .contentCommitment)
      try container.encode(self.keyEncipherment, forKey: .keyEncipherment)
      try container.encode(self.dataEncipherment, forKey: .dataEncipherment)
      try container.encode(self.keyAgreement, forKey: .keyAgreement)
      try container.encode(self.certSign, forKey: .certSign)
      try container.encode(self.crlSign, forKey: .crlSign)
      try container.encode(self.encipherOnly, forKey: .encipherOnly)
      try container.encode(self.decipherOnly, forKey: .decipherOnly)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.security.privateca.v1.KeyUsage.KeyUsageOptions"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// [KeyUsage.ExtendedKeyUsageOptions][google.cloud.security.privateca.v1.KeyUsage.ExtendedKeyUsageOptions]
  /// has fields that correspond to certain common OIDs that could be specified
  /// as an extended key usage value.
  ///
  /// [google.cloud.security.privateca.v1.KeyUsage.ExtendedKeyUsageOptions]: <doc:KeyUsage/ExtendedKeyUsageOptions>
  public struct ExtendedKeyUsageOptions: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Corresponds to OID 1.3.6.1.5.5.7.3.1. Officially described as "TLS WWW
    /// server authentication", though regularly used for non-WWW TLS.
    public var serverAuth: Swift.Bool = Swift.Bool()

    /// Corresponds to OID 1.3.6.1.5.5.7.3.2. Officially described as "TLS WWW
    /// client authentication", though regularly used for non-WWW TLS.
    public var clientAuth: Swift.Bool = Swift.Bool()

    /// Corresponds to OID 1.3.6.1.5.5.7.3.3. Officially described as "Signing of
    /// downloadable executable code client authentication".
    public var codeSigning: Swift.Bool = Swift.Bool()

    /// Corresponds to OID 1.3.6.1.5.5.7.3.4. Officially described as "Email
    /// protection".
    public var emailProtection: Swift.Bool = Swift.Bool()

    /// Corresponds to OID 1.3.6.1.5.5.7.3.8. Officially described as "Binding
    /// the hash of an object to a time".
    public var timeStamping: Swift.Bool = Swift.Bool()

    /// Corresponds to OID 1.3.6.1.5.5.7.3.9. Officially described as "Signing
    /// OCSP responses".
    public var ocspSigning: Swift.Bool = Swift.Bool()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ExtendedKeyUsageOptions`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ExtendedKeyUsageOptions().with { $0.serverAuth = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let serverAuth = CodingKeys(stringValue: "serverAuth")
      static let clientAuth = CodingKeys(stringValue: "clientAuth")
      static let codeSigning = CodingKeys(stringValue: "codeSigning")
      static let emailProtection = CodingKeys(stringValue: "emailProtection")
      static let timeStamping = CodingKeys(stringValue: "timeStamping")
      static let ocspSigning = CodingKeys(stringValue: "ocspSigning")

      static let _knownKeys: Set<Swift.String> = [
        "serverAuth",
        "clientAuth",
        "codeSigning",
        "emailProtection",
        "timeStamping",
        "ocspSigning",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .serverAuth) {
        self.serverAuth = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .clientAuth) {
        self.clientAuth = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .codeSigning) {
        self.codeSigning = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .emailProtection) {
        self.emailProtection = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .timeStamping) {
        self.timeStamping = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .ocspSigning) {
        self.ocspSigning = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.serverAuth, forKey: .serverAuth)
      try container.encode(self.clientAuth, forKey: .clientAuth)
      try container.encode(self.codeSigning, forKey: .codeSigning)
      try container.encode(self.emailProtection, forKey: .emailProtection)
      try container.encode(self.timeStamping, forKey: .timeStamping)
      try container.encode(self.ocspSigning, forKey: .ocspSigning)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.security.privateca.v1.KeyUsage.ExtendedKeyUsageOptions"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.security.privateca.v1.KeyUsage"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
