// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Request message for
/// [CertificateAuthorityService.ListCertificates][google.cloud.security.privateca.v1.CertificateAuthorityService.ListCertificates].
///
/// [google.cloud.security.privateca.v1.CertificateAuthorityService.ListCertificates]: <doc:CertificateAuthorityServiceClient/listCertificates(request:options:)>
public struct ListCertificatesRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the parent associated with the
  /// [Certificates][google.cloud.security.privateca.v1.Certificate], in the
  /// format `projects/*/locations/*/caPools/*`. The parent resource name can be
  /// in one of two forms:
  ///
  /// 1.  **Specific CA Pool:** To list certificates within a single CA Pool:
  ///     `projects/*/locations/*/caPools/*`
  ///
  /// 2.  **All CA Pools in a Location:** To list certificates across *all* CA
  ///     Pools in a given project and location, use the wildcard character (`-`)
  ///     in place of the CA Pool ID.
  ///     Example: `projects/*/locations/*/caPools/-`
  ///
  /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
  public var parent: Swift.String = Swift.String()

  /// Optional. Limit on the number of
  /// [Certificates][google.cloud.security.privateca.v1.Certificate] to include
  /// in the response. Further
  /// [Certificates][google.cloud.security.privateca.v1.Certificate] can
  /// subsequently be obtained by including the
  /// [ListCertificatesResponse.next_page_token][google.cloud.security.privateca.v1.ListCertificatesResponse.next_page_token]
  /// in a subsequent request. If unspecified, the server will pick an
  /// appropriate default.
  ///
  /// [google.cloud.security.privateca.v1.Certificate]: <doc:Certificate>
  /// [google.cloud.security.privateca.v1.ListCertificatesResponse.next_page_token]: <doc:ListCertificatesResponse/nextPageToken>
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. Pagination token, returned earlier via
  /// [ListCertificatesResponse.next_page_token][google.cloud.security.privateca.v1.ListCertificatesResponse.next_page_token].
  ///
  /// [google.cloud.security.privateca.v1.ListCertificatesResponse.next_page_token]: <doc:ListCertificatesResponse/nextPageToken>
  public var pageToken: Swift.String = Swift.String()

  /// Optional. Only include resources that match the filter in the response. For
  /// details on supported filters and syntax, see [Certificates Filtering
  /// documentation](https://cloud.google.com/certificate-authority-service/docs/sorting-filtering-certificates#filtering_support).
  public var filter: Swift.String = Swift.String()

  /// Optional. Specify how the results should be sorted. For details on
  /// supported fields and syntax, see [Certificates Sorting
  /// documentation](https://cloud.google.com/certificate-authority-service/docs/sorting-filtering-certificates#sorting_support).
  public var orderBy: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ListCertificatesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListCertificatesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let pageSize = CodingKeys(stringValue: "pageSize")
    static let pageToken = CodingKeys(stringValue: "pageToken")
    static let filter = CodingKeys(stringValue: "filter")
    static let orderBy = CodingKeys(stringValue: "orderBy")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "pageSize",
      "pageToken",
      "filter",
      "orderBy",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .pageSize) {
      self.pageSize = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken) {
      self.pageToken = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .filter) {
      self.filter = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .orderBy) {
      self.orderBy = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.pageSize, forKey: .pageSize)
    try container.encode(self.pageToken, forKey: .pageToken)
    try container.encode(self.filter, forKey: .filter)
    try container.encode(self.orderBy, forKey: .orderBy)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.security.privateca.v1.ListCertificatesRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
