// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleGax
@_spi(GoogleCloudInternal) import GoogleWKT

/// Response message for
/// [CertificateAuthorityService.ListCertificateTemplates][google.cloud.security.privateca.v1.CertificateAuthorityService.ListCertificateTemplates].
///
/// [google.cloud.security.privateca.v1.CertificateAuthorityService.ListCertificateTemplates]: <doc:CertificateAuthorityServiceClient/listCertificateTemplates(request:options:)>
public struct ListCertificateTemplatesResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The list of
  /// [CertificateTemplates][google.cloud.security.privateca.v1.CertificateTemplate].
  ///
  /// [google.cloud.security.privateca.v1.CertificateTemplate]: <doc:CertificateTemplate>
  public var certificateTemplates: [CertificateTemplate] = []

  /// A token to retrieve next page of results. Pass this value in
  /// [ListCertificateTemplatesRequest.page_token][google.cloud.security.privateca.v1.ListCertificateTemplatesRequest.page_token]
  /// to retrieve the next page of results.
  ///
  /// [google.cloud.security.privateca.v1.ListCertificateTemplatesRequest.page_token]: <doc:ListCertificateTemplatesRequest/pageToken>
  public var nextPageToken: Swift.String = Swift.String()

  /// A list of locations (e.g. "us-west1") that could not be reached.
  public var unreachable: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ListCertificateTemplatesResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListCertificateTemplatesResponse().with { $0.certificateTemplates = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let certificateTemplates = CodingKeys(stringValue: "certificateTemplates")
    static let nextPageToken = CodingKeys(stringValue: "nextPageToken")
    static let unreachable = CodingKeys(stringValue: "unreachable")

    static let _knownKeys: Set<Swift.String> = [
      "certificateTemplates",
      "nextPageToken",
      "unreachable",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [CertificateTemplate].self, forKey: .certificateTemplates)
    {
      self.certificateTemplates = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nextPageToken) {
      self.nextPageToken = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .unreachable) {
      self.unreachable = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.certificateTemplates, forKey: .certificateTemplates)
    try container.encode(self.nextPageToken, forKey: .nextPageToken)
    try container.encode(self.unreachable, forKey: .unreachable)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.security.privateca.v1.ListCertificateTemplatesResponse"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}

@_spi(GoogleCloudInternal)
extension ListCertificateTemplatesResponse: GoogleGax._PaginatedResponse {
  public func _getPaginatedItems() -> [CertificateTemplate] {
    return self.certificateTemplates
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
