// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// [SubjectAltNames][google.cloud.security.privateca.v1.SubjectAltNames]
/// corresponds to a more modern way of listing what the asserted identity is in
/// a certificate (i.e., compared to the "common name" in the distinguished
/// name).
///
/// [google.cloud.security.privateca.v1.SubjectAltNames]: <doc:SubjectAltNames>
public struct SubjectAltNames: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Contains only valid, fully-qualified host names.
  public var dnsNames: [Swift.String] = []

  /// Contains only valid RFC 3986 URIs.
  public var uris: [Swift.String] = []

  /// Contains only valid RFC 2822 E-mail addresses.
  public var emailAddresses: [Swift.String] = []

  /// Contains only valid 32-bit IPv4 addresses or RFC 4291 IPv6 addresses.
  public var ipAddresses: [Swift.String] = []

  /// Contains additional subject alternative name values.
  /// For each custom_san, the `value` field must contain an ASN.1 encoded
  /// UTF8String.
  public var customSans: [X509Extension] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SubjectAltNames`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SubjectAltNames().with { $0.dnsNames = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let dnsNames = CodingKeys(stringValue: "dnsNames")
    static let uris = CodingKeys(stringValue: "uris")
    static let emailAddresses = CodingKeys(stringValue: "emailAddresses")
    static let ipAddresses = CodingKeys(stringValue: "ipAddresses")
    static let customSans = CodingKeys(stringValue: "customSans")

    static let _knownKeys: Set<Swift.String> = [
      "dnsNames",
      "uris",
      "emailAddresses",
      "ipAddresses",
      "customSans",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .dnsNames) {
      self.dnsNames = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .uris) {
      self.uris = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .emailAddresses) {
      self.emailAddresses = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .ipAddresses) {
      self.ipAddresses = value
    }
    if let value = try container.decodeIfPresent([X509Extension].self, forKey: .customSans) {
      self.customSans = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.dnsNames, forKey: .dnsNames)
    try container.encode(self.uris, forKey: .uris)
    try container.encode(self.emailAddresses, forKey: .emailAddresses)
    try container.encode(self.ipAddresses, forKey: .ipAddresses)
    try container.encode(self.customSans, forKey: .customSans)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.security.privateca.v1.SubjectAltNames"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
