// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// [Subject][google.cloud.security.privateca.v1.Subject] describes parts of a
/// distinguished name that, in turn, describes the subject of the certificate.
///
/// [google.cloud.security.privateca.v1.Subject]: <doc:Subject>
public struct Subject: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The "common name" of the subject.
  public var commonName: Swift.String = Swift.String()

  /// The country code of the subject.
  public var countryCode: Swift.String = Swift.String()

  /// The organization of the subject.
  public var organization: Swift.String = Swift.String()

  /// The organizational_unit of the subject.
  public var organizationalUnit: Swift.String = Swift.String()

  /// The locality or city of the subject.
  public var locality: Swift.String = Swift.String()

  /// The province, territory, or regional state of the subject.
  public var province: Swift.String = Swift.String()

  /// The street address of the subject.
  public var streetAddress: Swift.String = Swift.String()

  /// The postal code of the subject.
  public var postalCode: Swift.String = Swift.String()

  /// This field can be used in place of the named subject fields.
  public var rdnSequence: [RelativeDistinguishedName] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Subject`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Subject().with { $0.commonName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let commonName = CodingKeys(stringValue: "commonName")
    static let countryCode = CodingKeys(stringValue: "countryCode")
    static let organization = CodingKeys(stringValue: "organization")
    static let organizationalUnit = CodingKeys(stringValue: "organizationalUnit")
    static let locality = CodingKeys(stringValue: "locality")
    static let province = CodingKeys(stringValue: "province")
    static let streetAddress = CodingKeys(stringValue: "streetAddress")
    static let postalCode = CodingKeys(stringValue: "postalCode")
    static let rdnSequence = CodingKeys(stringValue: "rdnSequence")

    static let _knownKeys: Set<Swift.String> = [
      "commonName",
      "countryCode",
      "organization",
      "organizationalUnit",
      "locality",
      "province",
      "streetAddress",
      "postalCode",
      "rdnSequence",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .commonName) {
      self.commonName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .countryCode) {
      self.countryCode = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .organization) {
      self.organization = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .organizationalUnit) {
      self.organizationalUnit = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .locality) {
      self.locality = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .province) {
      self.province = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .streetAddress) {
      self.streetAddress = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .postalCode) {
      self.postalCode = value
    }
    if let value = try container.decodeIfPresent(
      [RelativeDistinguishedName].self, forKey: .rdnSequence)
    {
      self.rdnSequence = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.commonName, forKey: .commonName)
    try container.encode(self.countryCode, forKey: .countryCode)
    try container.encode(self.organization, forKey: .organization)
    try container.encode(self.organizationalUnit, forKey: .organizationalUnit)
    try container.encode(self.locality, forKey: .locality)
    try container.encode(self.province, forKey: .province)
    try container.encode(self.streetAddress, forKey: .streetAddress)
    try container.encode(self.postalCode, forKey: .postalCode)
    try container.encode(self.rdnSequence, forKey: .rdnSequence)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.security.privateca.v1.Subject"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
