// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An [X509Parameters][google.cloud.security.privateca.v1.X509Parameters] is
/// used to describe certain fields of an X.509 certificate, such as the key
/// usage fields, fields specific to CA certificates, certificate policy
/// extensions and custom extensions.
///
/// [google.cloud.security.privateca.v1.X509Parameters]: <doc:X509Parameters>
public struct X509Parameters: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Indicates the intended use for keys that correspond to a
  /// certificate.
  public var keyUsage: KeyUsage? = nil

  /// Optional. Describes options in this
  /// [X509Parameters][google.cloud.security.privateca.v1.X509Parameters] that
  /// are relevant in a CA certificate. If not specified, a default basic
  /// constraints extension with `is_ca=false` will be added for leaf
  /// certificates.
  ///
  /// [google.cloud.security.privateca.v1.X509Parameters]: <doc:X509Parameters>
  public var caOptions: X509Parameters.CaOptions? = nil

  /// Optional. Describes the X.509 certificate policy object identifiers, per
  /// https://tools.ietf.org/html/rfc5280#section-4.2.1.4.
  public var policyIds: [ObjectId] = []

  /// Optional. Describes Online Certificate Status Protocol (OCSP) endpoint
  /// addresses that appear in the "Authority Information Access" extension in
  /// the certificate.
  public var aiaOcspServers: [Swift.String] = []

  /// Optional. Describes the X.509 name constraints extension.
  public var nameConstraints: X509Parameters.NameConstraints? = nil

  /// Optional. Describes custom X.509 extensions.
  public var additionalExtensions: [X509Extension] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `X509Parameters`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = X509Parameters().with { $0.keyUsage = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let keyUsage = CodingKeys(stringValue: "keyUsage")
    static let caOptions = CodingKeys(stringValue: "caOptions")
    static let policyIds = CodingKeys(stringValue: "policyIds")
    static let aiaOcspServers = CodingKeys(stringValue: "aiaOcspServers")
    static let nameConstraints = CodingKeys(stringValue: "nameConstraints")
    static let additionalExtensions = CodingKeys(stringValue: "additionalExtensions")

    static let _knownKeys: Set<Swift.String> = [
      "keyUsage",
      "caOptions",
      "policyIds",
      "aiaOcspServers",
      "nameConstraints",
      "additionalExtensions",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.keyUsage = try container.decodeIfPresent(KeyUsage.self, forKey: .keyUsage)
    self.caOptions = try container.decodeIfPresent(
      X509Parameters.CaOptions.self, forKey: .caOptions)
    if let value = try container.decodeIfPresent([ObjectId].self, forKey: .policyIds) {
      self.policyIds = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .aiaOcspServers) {
      self.aiaOcspServers = value
    }
    self.nameConstraints = try container.decodeIfPresent(
      X509Parameters.NameConstraints.self, forKey: .nameConstraints)
    if let value = try container.decodeIfPresent(
      [X509Extension].self, forKey: .additionalExtensions)
    {
      self.additionalExtensions = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.keyUsage, forKey: .keyUsage)
    try container.encodeIfPresent(self.caOptions, forKey: .caOptions)
    try container.encode(self.policyIds, forKey: .policyIds)
    try container.encode(self.aiaOcspServers, forKey: .aiaOcspServers)
    try container.encodeIfPresent(self.nameConstraints, forKey: .nameConstraints)
    try container.encode(self.additionalExtensions, forKey: .additionalExtensions)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Describes the X.509 basic constraints extension, per [RFC 5280
  /// section 4.2.1.9](https://tools.ietf.org/html/rfc5280#section-4.2.1.9)
  public struct CaOptions: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. Refers to the "CA" boolean field in the X.509 extension.
    /// When this value is missing, the basic constraints extension will be
    /// omitted from the certificate.
    public var isCa: Swift.Bool? = nil

    /// Optional. Refers to the path length constraint field in the X.509
    /// extension. For a CA certificate, this value describes the depth of
    /// subordinate CA certificates that are allowed. If this value is less than
    /// 0, the request will fail. If this value is missing, the max path length
    /// will be omitted from the certificate.
    public var maxIssuerPathLength: Swift.Int32? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `CaOptions`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CaOptions().with { $0.isCa = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let isCa = CodingKeys(stringValue: "isCa")
      static let maxIssuerPathLength = CodingKeys(stringValue: "maxIssuerPathLength")

      static let _knownKeys: Set<Swift.String> = [
        "isCa",
        "maxIssuerPathLength",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.isCa = try container.decodeIfPresent(Swift.Bool.self, forKey: .isCa)
      self.maxIssuerPathLength = try container.decodeIfPresent(
        Swift.Int32.self, forKey: .maxIssuerPathLength)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.isCa, forKey: .isCa)
      try container.encodeIfPresent(self.maxIssuerPathLength, forKey: .maxIssuerPathLength)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.security.privateca.v1.X509Parameters.CaOptions"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Describes the X.509 name constraints extension, per
  /// https://tools.ietf.org/html/rfc5280#section-4.2.1.10
  public struct NameConstraints: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Indicates whether or not the name constraints are marked critical.
    public var critical: Swift.Bool = Swift.Bool()

    /// Contains permitted DNS names. Any DNS name that can be
    /// constructed by simply adding zero or more labels to
    /// the left-hand side of the name satisfies the name constraint.
    /// For example, `example.com`, `www.example.com`, `www.sub.example.com`
    /// would satisfy `example.com` while `example1.com` does not.
    public var permittedDnsNames: [Swift.String] = []

    /// Contains excluded DNS names. Any DNS name that can be
    /// constructed by simply adding zero or more labels to
    /// the left-hand side of the name satisfies the name constraint.
    /// For example, `example.com`, `www.example.com`, `www.sub.example.com`
    /// would satisfy `example.com` while `example1.com` does not.
    public var excludedDnsNames: [Swift.String] = []

    /// Contains the permitted IP ranges. For IPv4 addresses, the ranges
    /// are expressed using CIDR notation as specified in RFC 4632.
    /// For IPv6 addresses, the ranges are expressed in similar encoding as IPv4
    /// addresses.
    public var permittedIpRanges: [Swift.String] = []

    /// Contains the excluded IP ranges. For IPv4 addresses, the ranges
    /// are expressed using CIDR notation as specified in RFC 4632.
    /// For IPv6 addresses, the ranges are expressed in similar encoding as IPv4
    /// addresses.
    public var excludedIpRanges: [Swift.String] = []

    /// Contains the permitted email addresses. The value can be a particular
    /// email address, a hostname to indicate all email addresses on that host or
    /// a domain with a leading period (e.g. `.example.com`) to indicate
    /// all email addresses in that domain.
    public var permittedEmailAddresses: [Swift.String] = []

    /// Contains the excluded email addresses. The value can be a particular
    /// email address, a hostname to indicate all email addresses on that host or
    /// a domain with a leading period (e.g. `.example.com`) to indicate
    /// all email addresses in that domain.
    public var excludedEmailAddresses: [Swift.String] = []

    /// Contains the permitted URIs that apply to the host part of the name.
    /// The value can be a hostname or a domain with a
    /// leading period (like `.example.com`)
    public var permittedUris: [Swift.String] = []

    /// Contains the excluded URIs that apply to the host part of the name.
    /// The value can be a hostname or a domain with a
    /// leading period (like `.example.com`)
    public var excludedUris: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `NameConstraints`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = NameConstraints().with { $0.critical = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let critical = CodingKeys(stringValue: "critical")
      static let permittedDnsNames = CodingKeys(stringValue: "permittedDnsNames")
      static let excludedDnsNames = CodingKeys(stringValue: "excludedDnsNames")
      static let permittedIpRanges = CodingKeys(stringValue: "permittedIpRanges")
      static let excludedIpRanges = CodingKeys(stringValue: "excludedIpRanges")
      static let permittedEmailAddresses = CodingKeys(stringValue: "permittedEmailAddresses")
      static let excludedEmailAddresses = CodingKeys(stringValue: "excludedEmailAddresses")
      static let permittedUris = CodingKeys(stringValue: "permittedUris")
      static let excludedUris = CodingKeys(stringValue: "excludedUris")

      static let _knownKeys: Set<Swift.String> = [
        "critical",
        "permittedDnsNames",
        "excludedDnsNames",
        "permittedIpRanges",
        "excludedIpRanges",
        "permittedEmailAddresses",
        "excludedEmailAddresses",
        "permittedUris",
        "excludedUris",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .critical) {
        self.critical = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .permittedDnsNames)
      {
        self.permittedDnsNames = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .excludedDnsNames) {
        self.excludedDnsNames = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .permittedIpRanges)
      {
        self.permittedIpRanges = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .excludedIpRanges) {
        self.excludedIpRanges = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String].self, forKey: .permittedEmailAddresses)
      {
        self.permittedEmailAddresses = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String].self, forKey: .excludedEmailAddresses)
      {
        self.excludedEmailAddresses = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .permittedUris) {
        self.permittedUris = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .excludedUris) {
        self.excludedUris = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.critical, forKey: .critical)
      try container.encode(self.permittedDnsNames, forKey: .permittedDnsNames)
      try container.encode(self.excludedDnsNames, forKey: .excludedDnsNames)
      try container.encode(self.permittedIpRanges, forKey: .permittedIpRanges)
      try container.encode(self.excludedIpRanges, forKey: .excludedIpRanges)
      try container.encode(self.permittedEmailAddresses, forKey: .permittedEmailAddresses)
      try container.encode(self.excludedEmailAddresses, forKey: .excludedEmailAddresses)
      try container.encode(self.permittedUris, forKey: .permittedUris)
      try container.encode(self.excludedUris, forKey: .excludedUris)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.security.privateca.v1.X509Parameters.NameConstraints"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.security.privateca.v1.X509Parameters"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
